import { useState } from "react";
import { Bell, BookmarkSimple, CaretRight, Check, CheckCircle, ClockCounterClockwise, FileText, Globe, House, MagnifyingGlass, Plus, ShieldCheck, UserCircle, X } from "@phosphor-icons/react";
import { EmptyState, PageHeader } from "../components/Common.jsx";

const savedItems = [
  { title: "Who supports a state-issued e-ID?", type: "Evidence collection", meta: "4 moments · Updated yesterday", icon: BookmarkSimple },
  { title: "Private providers AND data protection", type: "Saved search", meta: "128 results · Updated 12 Sep", icon: MagnifyingGlass },
  { title: "Electronic identity: final vote briefing", type: "AI briefing", meta: "9 sources · Updated 10 Sep", icon: Globe },
];
export function SavedResearchScreen({ onRoute }) {
  const [filter,setFilter] = useState("All"); const [query,setQuery] = useState("");
  const visibleItems = (filter === "All" ? savedItems : savedItems.filter(item => item.type === filter)).filter(item => item.title.toLowerCase().includes(query.toLowerCase()));
  return <main className="page-stage library-page"><PageHeader eyebrow="Your workspace" title="Saved Research" description="Return to evidence, searches, and briefings you chose to keep." actions={<button className="primary-action" onClick={() => onRoute("investigate")}><Plus /> New research</button>} /><div className="library-toolbar"><div>{["All","Evidence collection","Saved search","AI briefing"].map(item => <button key={item} className={filter === item ? "active" : ""} onClick={() => setFilter(item)}>{item}</button>)}</div><label><MagnifyingGlass /><input aria-label="Search saved research" value={query} onChange={e => setQuery(e.target.value)} placeholder="Search saved research..." /></label></div>{visibleItems.length === 0 ? <EmptyState title="No saved research matches" message="Try a different search or clear the active filter." actionLabel="Clear search" onAction={() => { setQuery(""); setFilter("All"); }} /> : <section className="library-list">{visibleItems.map(item => { const Icon = item.icon; return <button key={item.title} onClick={() => onRoute(item.type === "Evidence collection" || item.type === "Saved search" ? "investigate" : "ask")}><span className="library-icon"><Icon /></span><span><small>{item.type}</small><strong>{item.title}</strong><em>{item.meta}</em></span><CaretRight /></button>; })}</section>}</main>;
}

export function HistoryScreen({ onRoute }) {
  const [cleared,setCleared] = useState(false);
  const groups = [{ date:"Today", items:[{title:"What were the main disagreements about the electronic identity proposal?",meta:"Ask Parliament · 14:32",route:"ask"},{title:"Electronic identity (e-ID)",meta:"Debate viewed · 14:18",route:"debate"}]},{date:"Yesterday",items:[{title:"Who supports a state-issued e-ID?",meta:"Evidence collection · 17:06",route:"investigate"},{title:"Federal Act on Electronic Identity",meta:"Proposal viewed · 16:42",route:"proposal"}]}];
  return <main className="page-stage library-page"><PageHeader eyebrow="Recent activity" title="History" description="Your private record of briefings, debates, and research sessions." actions={<button className="secondary-action" onClick={() => setCleared(true)}><X /> Clear history</button>} />{cleared ? <section className="history-empty"><ClockCounterClockwise /><h2>History cleared</h2><p>New activity will appear here as you use the workspace.</p><button className="primary-action" onClick={() => onRoute("dashboard")}><House /> Return to dashboard</button></section> : <div className="history-groups">{groups.map(group => <section key={group.date}><h2>{group.date}</h2>{group.items.map(item => <button key={item.title} onClick={() => onRoute(item.route)}><ClockCounterClockwise /><span><strong>{item.title}</strong><small>{item.meta}</small></span><CaretRight /></button>)}</section>)}</div>}</main>;
}

export function SettingsScreen({ userName, setUserName, language, setLanguage }) {
  const [draftName,setDraftName] = useState(userName); const [saved,setSaved] = useState(false); const [tab,setTab] = useState("Profile");
  const save = e => { e.preventDefault(); setUserName(draftName.trim() || "Citizen"); setSaved(true); setTimeout(() => setSaved(false),1600); };
  return <main className="page-stage settings-page"><PageHeader eyebrow="Account" title="Settings" description="Manage your profile, language, notifications, and privacy." /><div className="settings-layout"><aside>{[UserCircle,Bell,ShieldCheck].map((Icon,index) => { const item=["Profile","Notifications","Privacy"][index]; return <button key={item} className={tab === item ? "active" : ""} onClick={() => setTab(item)}><Icon /> {item}</button>; })}</aside><section className="settings-panel">{tab === "Profile" && <form onSubmit={save}><div className="settings-heading"><div className="profile-avatar"><UserCircle weight="fill" /></div><div><h2>Profile</h2><p>This name personalizes your dashboard greeting.</p></div></div><label>Display name<input value={draftName} onChange={e => setDraftName(e.target.value)} placeholder="Citizen" /></label><label>Email address<input value="citizen@example.ch" readOnly /><small>Mock account data for the prototype.</small></label><fieldset><legend>Interface language</legend><div className="language-options">{["DE","FR","IT","EN"].map(item => <button type="button" key={item} className={language === item ? "active" : ""} onClick={() => setLanguage(item)}>{item}</button>)}</div></fieldset><div className="settings-actions"><button className="primary-action" type="submit">{saved ? <CheckCircle weight="fill" /> : <Check />}{saved ? "Changes saved" : "Save changes"}</button></div></form>}{tab === "Notifications" && <div><div className="settings-heading"><Bell /><div><h2>Notifications</h2><p>Choose which followed activity should reach you.</p></div></div><div className="setting-toggles">{[["Proposal status changes","Stage changes and upcoming votes"],["New debate evidence","New moments matching followed topics"],["Weekly research digest","A concise summary every Monday"]].map(([title,meta],index) => <label key={title}><span><strong>{title}</strong><small>{meta}</small></span><input type="checkbox" defaultChecked={index < 2} /></label>)}</div></div>}{tab === "Privacy" && <div><div className="settings-heading"><ShieldCheck /><div><h2>Privacy</h2><p>Control how your private workspace data is handled.</p></div></div><div className="privacy-note"><ShieldCheck weight="fill" /><div><strong>Your political affiliation is never inferred</strong><p>Dashboard recommendations use only the people, proposals, and topics you explicitly follow.</p></div></div><div className="setting-toggles"><label><span><strong>Save activity history</strong><small>Keep a private list of pages and research you opened</small></span><input type="checkbox" defaultChecked /></label><label><span><strong>Product improvement analytics</strong><small>Share anonymous interaction data</small></span><input type="checkbox" /></label></div></div>}</section></div></main>;
}
