import React,{useEffect,useState} from 'react';
import {GoogleLogo,AppleLogo,DiscordLogo,Buildings,Eye,EyeSlash} from '@phosphor-icons/react';
import {pilotApi as api} from '../services/pilotApi.js';
import './account.css';
export default function AuthPanel({user,onUser,onClose,initialMode='login',onGuest}){
 const [mode,setMode]=useState(initialMode),[providers,setProviders]=useState(null),[busy,setBusy]=useState(false),[note,setNote]=useState(''),[showPassword,setShowPassword]=useState(false);
 useEffect(()=>{let active=true;api.providers().then(p=>active&&setProviders(p)).catch(()=>active&&setNote('Account service unavailable. Please try again.'));return()=>{active=false;};},[]);
 const titles={login:'Welcome back.',signup:'Your own perspective.\nA place to keep it.',recover:'Let’s get you back in.',reset:'A fresh start.'};
 const change=m=>{setMode(m);setNote('');setShowPassword(false);};
 async function submit(e){e.preventDefault();setBusy(true);setNote('');const d=Object.fromEntries(new FormData(e.currentTarget));try{if(mode==='recover'){await api.recover({email:d.email});setNote('If this address has an account, a recovery link is on its way. Open it in this browser within one hour.');}else if(mode==='reset'){await api.password({password:d.password});setNote('Password updated. You can continue researching.');}else{const r=await api[mode](d);if(r.status==='check-email')setNote('Check your inbox. Open the verification link in this browser within one hour. Already verified elsewhere? Sign in here.');else{onUser(r);onClose();}}}catch(e){setNote(({EMAIL_NOT_CONFIRMED:'Please verify your email before signing in.',AUTH_RATE_LIMITED:'Too many attempts. Please wait before trying again.',AUTH_FAILED:'We couldn’t complete that request. Check your details and try again.'})[e.message]||'Account service unavailable. Please try again.');}finally{setBusy(false);}}
 async function social(provider){setBusy(true);setNote('');try{const r=await api.provider(provider);location.assign(r.url);}catch{setNote('This sign-in method could not start. Try email or return later.');setBusy(false);}}
 return <div className="auth-panel account-refined"><img className="account-guide" src={import.meta.env.BASE_URL+'images/cleisthenes.png'} alt=""/><p className="account-eyebrow">MIDNIGHT.VOTE · SWISS PILOT</p><h2 id="account-title">{user&&mode!=='reset'?'Your account':titles[mode]}</h2>
 {user&&mode!=='reset'?<><p>{user.name||user.email}</p><small>{user.email}</small><button className="account-submit" disabled={busy} onClick={async()=>{setBusy(true);try{await api.logout();onUser(null);onClose();}catch{setNote('Sign-out failed. Please try again.');}finally{setBusy(false);}}}>Sign out</button></>:<>
 <p className="account-intro">{mode==='signup'?'Keep your sources, follow topics and pick up where you left off.':mode==='login'?'Your sources and conversations, together again.':'Use the email address associated with your account.'}</p>
 {['login','signup'].includes(mode)&&<><div className="account-providers">{[['google','Google',GoogleLogo],['apple','Apple',AppleLogo],['discord','Discord',DiscordLogo]].map(([id,label,Icon])=><button key={id} type="button" disabled={busy||!providers?.[id]} onClick={()=>social(id)} aria-label={'Continue with '+label+(!providers?.[id]?' — not enabled':'')}><Icon size={21}/><span>{label}</span></button>)}</div>{providers&&!['google','apple','discord'].some(p=>providers[p])&&<small className="account-provider-note">Social sign-in is not enabled yet.</small>}<div className="account-divider"><span>Continue with email</span></div></>}
 {providers?.email?<form onSubmit={submit}>{mode!=='reset'&&<label>Email address<input name="email" type="email" required maxLength={254} autoComplete="email" placeholder="you@example.ch"/></label>}{mode!=='recover'&&<label>Password<div className="account-password"><input name="password" type={showPassword?'text':'password'} required minLength={8} maxLength={256} autoComplete={mode==='login'?'current-password':'new-password'}/><button type="button" aria-label={showPassword?'Hide password':'Show password'} onClick={()=>setShowPassword(v=>!v)}>{showPassword?<EyeSlash size={19}/>:<Eye size={19}/>}</button></div>{mode!=='login'&&<small>At least 8 characters</small>}</label>}<button className="account-submit" disabled={busy}>{busy?'Please wait…':({login:'Sign in',signup:'Create my account',recover:'Send recovery link',reset:'Update password'})[mode]}</button></form>:<p role="status">{providers?'Email accounts are unavailable.':'Connecting to account service…'}</p>}
 <div className="auth-links">{mode==='signup'?<span>Already have an account? <button disabled={busy} onClick={()=>change('login')}>Sign in</button></span>:mode==='login'?<><button disabled={busy} onClick={()=>change('signup')}>Create an account</button><button disabled={busy} onClick={()=>change('recover')}>Forgot password?</button></>:<button disabled={busy} onClick={()=>change('login')}>Back to sign in</button>}</div>
 {['login','signup'].includes(mode)&&<button className="account-sso" disabled={busy||!providers?.sso} onClick={()=>social('sso')}><Buildings size={17}/> Organization SSO{!providers?.sso&&<small>Not enabled</small>}</button>}
 {onGuest&&<button className="account-guest" onClick={onGuest}>Explore without an account →</button>}
 <small className="account-footnote">Public reading stays open. No wallet or identity document needed.</small></>}
 {note&&<p className="account-notice" role="status">{note}</p>}</div>;
}
