import React,{useEffect,useState} from 'react';
import {pilotApi as api} from '../services/pilotApi.js';
export default function AuthPanel({user,onUser,onClose,initialMode='login'}){
 const [mode,setMode]=useState(initialMode),[providers,setProviders]=useState(null),[busy,setBusy]=useState(false),[note,setNote]=useState('');
 useEffect(()=>{api.providers().then(setProviders).catch(()=>setNote('Account service unavailable. Please try again.'));},[]);
 const titles={login:'Welcome back',signup:'Create your account',recover:'Reset your password',reset:'Choose a new password'};
 const change=m=>{setMode(m);setNote('');};
 async function submit(e){e.preventDefault();setBusy(true);setNote('');const d=Object.fromEntries(new FormData(e.currentTarget));try{if(mode==='recover'){await api.recover({email:d.email});setNote('If this address has an account, a recovery link is on its way. Open it in this browser within one hour.');}else if(mode==='reset'){await api.password({password:d.password});setNote('Password updated. You can continue researching.');}else{const r=await api[mode](d);if(r.status==='check-email')setNote('Check your email. Open the verification link in this browser within one hour; on another device, verify your email and then sign in.');else{onUser(r);onClose();}}}catch(e){setNote(({EMAIL_NOT_CONFIRMED:'Please verify your email before signing in.',AUTH_RATE_LIMITED:'Too many attempts. Please wait before trying again.',AUTH_FAILED:'We couldn’t complete that request. Check your details and try again.',GOOGLE_NOT_CONFIGURED:'Google sign-in is not available yet.'})[e.message]||'Account service unavailable. Please try again.');}finally{setBusy(false);}}
 return <div className="auth-panel"><p className="eyebrow">Your civic workspace</p><h2>{user&&mode!=='reset'?'Your account':titles[mode]}</h2>{user&&mode!=='reset'?<><p>{user.name||user.email}</p><small>{user.email}</small><button className="primary" disabled={busy} onClick={async()=>{setBusy(true);try{await api.logout();onUser(null);onClose();}catch{setNote('Sign-out failed. Please try again.');}finally{setBusy(false);}}}>Sign out</button></>:<><p>{mode==='signup'?'Save sources, follow subjects and continue your conversations across devices.':'Public research is always available without an account.'}</p>{providers?.email?<form onSubmit={submit}>{mode==='signup'&&<label>Display name (optional)<input name="name" maxLength={100} autoComplete="nickname"/></label>}{mode!=='reset'&&<label>Email<input name="email" type="email" required maxLength={254} autoComplete="email"/></label>}{mode!=='recover'&&<label>Password<input name="password" type="password" required minLength={8} maxLength={256} autoComplete={mode==='login'?'current-password':'new-password'}/><small>At least 8 characters</small></label>}<button className="primary" disabled={busy}>{busy?'Please wait…':({login:'Sign in',signup:'Create account',recover:'Send recovery link',reset:'Update password'})[mode]}</button></form>:<p role="status">{providers?'Accounts are not configured.':'Connecting to account service…'}</p>}{['login','signup'].includes(mode)&&providers?.google&&<button className="secondary" disabled={busy} onClick={async()=>{setBusy(true);try{const r=await api.google();location.assign(r.url);}catch{setNote('Google sign-in could not start.');setBusy(false);}}}>Continue with Google</button>}<div className="auth-links">{mode!=='signup'&&mode!=='reset'&&<button onClick={()=>change('signup')}>Create an account</button>}{mode!=='login'&&<button onClick={()=>change('login')}>Back to sign in</button>}{mode==='login'&&<button onClick={()=>change('recover')}>Forgot password?</button>}</div></>}{note&&<p role="status">{note}</p>}</div>;
}
