import React,{useState,useEffect,useRef} from 'react';
import {pilotApi as api} from '../services/pilotApi.js';
import FollowButton from './FollowButton.jsx';
export default function Chamber({onProfile,onAsk,user,onAccount}){
 const [council,setCouncil]=useState('nr'),[snapshot,setSnapshot]=useState(null),[error,setError]=useState(''),[colorBy,setColorBy]=useState('party'),[highlight,setHighlight]=useState(null),[selected,setSelected]=useState(null),[hovered,setHovered]=useState(null),[query,setQuery]=useState(''),[view,setView]=useState([0,0,860,565]);
 const svg=useRef(null),drag=useRef(null),pointers=useRef(new Map()),moved=useRef(false);
 useEffect(()=>{let live=true;setSnapshot(null);setSelected(null);setHovered(null);setHighlight(null);setView([0,0,860,565]);setError('');api.chamber(council).then(s=>live&&setSnapshot(s)).catch(()=>live&&setError('A verified seating snapshot is unavailable. Open the official seating plan below.'));return()=>{live=false;};},[council]);
 const legend=snapshot?.[colorBy==='party'?'parties':'groups']||[],key=colorBy==='party'?'partyId':'groupId';
 const [broadcast,setBroadcast]=useState(null);useEffect(()=>{let live=true;const refresh=()=>{if(document.visibilityState==='visible')api.broadcast().then(r=>live&&setBroadcast(r)).catch(()=>live&&setBroadcast(null));};refresh();const timer=setInterval(refresh,60000);return()=>{live=false;clearInterval(timer);};},[]);
 const member=(selected||hovered)?.member;
 function choose(seat){setSelected(seat);setHovered(null);const b=svg.current?.querySelector('[data-seat="'+seat.seatId+'"]')?.getBBox();const x=b?b.x+b.width/2:seat.geometry.x,y=b?b.y+b.height/2:seat.geometry.y;setView([x-215,y-141.25,430,282.5]);}
 const zoom=f=>setView(([x,y,w,h])=>{const nw=Math.max(150,Math.min(1100,w*f)),nh=nw*565/860;return[x+(w-nw)/2,y+(h-nh)/2,nw,nh];});
 const filtered=(snapshot?.seats||[]).filter(s=>!query||`${s.member?.name} ${s.member?.canton} ${s.member?.party} ${s.seatId}`.normalize('NFD').replace(/\p{M}/gu,'').toLowerCase().includes(query.normalize('NFD').replace(/\p{M}/gu,'').toLowerCase()));
 return <section className="chamber-section" aria-label="Explore the chambers"><div className="workspace-heading"><div><p className="eyebrow">Inside the Federal Palace</p><h2>Every seat. Every voice.</h2></div><div className="workspace-segments" role="group" aria-label="Chamber"><button aria-pressed={council==='nr'} onClick={()=>setCouncil('nr')}>National Council <small>200</small></button><button aria-pressed={council==='sr'} onClick={()=>setCouncil('sr')}>Council of States <small>46</small></button></div></div>
 {error?<p role="alert">{error} <a href={'https://www.parlament.ch/de/organe/'+(council==='nr'?'nationalrat/sitzordnung-nr':'staenderat/sitzordnung-sr')} target="_blank" rel="noreferrer">Official plan ↗</a></p>:!snapshot?<p role="status">Loading verified seats…</p>:<><div className="chamber-meta"><strong>Seating as of {snapshot.asOf}</strong><span>{snapshot.counts.occupied} members · {snapshot.counts.vacant} vacancies</span><label>Colour by <select value={colorBy} onChange={e=>{setColorBy(e.target.value);setHighlight(null);}}><option value="party">Party / organisation</option><option value="group">Parliamentary group</option></select></label></div><div className="chamber-layout"><div className="chamber-map-panel"><div className="map-controls"><button aria-label="Zoom in" onClick={()=>zoom(.75)}>＋</button><button aria-label="Zoom out" onClick={()=>zoom(1.3)}>−</button><button onClick={()=>setView([0,0,860,565])}>Reset view</button><span>Drag to pan · select a desk</span></div>
 <svg ref={svg} className="chamber-svg" viewBox={view.join(' ')} aria-label={`${council==='nr'?'National Council':'Council of States'} official desk layout`} onPointerDown={e=>{pointers.current.set(e.pointerId,{x:e.clientX,y:e.clientY});moved.current=false;drag.current={x:e.clientX,y:e.clientY,view:[...view],distance:pointers.current.size===2?Math.hypot(...(()=>{const[a,b]=[...pointers.current.values()];return[a.x-b.x,a.y-b.y];})()):null};e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={e=>{if(!pointers.current.has(e.pointerId)||!drag.current)return;pointers.current.set(e.pointerId,{x:e.clientX,y:e.clientY});const d=drag.current,rect=e.currentTarget.getBoundingClientRect();if(pointers.current.size===2&&d.distance){const[a,b]=[...pointers.current.values()],distance=Math.hypot(a.x-b.x,a.y-b.y),nw=Math.max(150,Math.min(1100,d.view[2]*d.distance/Math.max(1,distance)));setView([d.view[0]+(d.view[2]-nw)/2,d.view[1]+(d.view[3]-nw*565/860)/2,nw,nw*565/860]);moved.current=true;}else if(Math.abs(e.clientX-d.x)+Math.abs(e.clientY-d.y)>5){moved.current=true;setView([d.view[0]-(e.clientX-d.x)*d.view[2]/rect.width,d.view[1]-(e.clientY-d.y)*d.view[3]/rect.height,d.view[2],d.view[3]]);}}} onPointerUp={e=>{if(!moved.current){const el=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-seat]');const seat=snapshot.seats.find(s=>s.seatId===el?.getAttribute('data-seat'));if(seat)choose(seat);}pointers.current.delete(e.pointerId);drag.current=null;}} onPointerCancel={()=>{pointers.current.clear();drag.current=null;}}>
 <defs><filter id="desk-shadow" x="-20%" y="-20%" width="150%" height="160%"><feDropShadow dx="0" dy="2" stdDeviation="1.3" floodColor="#51432b" floodOpacity=".22"/></filter>{legend.map(l=><pattern id={`seat-${council}-${colorBy}-${l.id}`} key={l.id} patternUnits="userSpaceOnUse" width="6" height="6"><rect width="6" height="6" fill={l.color}/>{l.pattern===1?<path d="M0 6L6 0" stroke="white" strokeOpacity=".32" strokeWidth="1"/>:l.pattern===2?<circle cx="3" cy="3" r=".8" fill="white" opacity=".48"/>:l.pattern===3?<path d="M0 3h6" stroke="white" strokeOpacity=".3"/>:null}</pattern>)}</defs>
 <g className="chamber-architecture">{snapshot.architecture.map((path,i)=><path key={i} d={path}/>)}</g>
 {snapshot.seats.map(s=>{const l=legend.find(l=>l.id===s.member?.[key]),active=selected?.seatId===s.seatId,dim=highlight&&highlight!==s.member?.[key];return <path key={s.seatId} data-seat={s.seatId} d={s.geometry.path} className={`chamber-seat ${active?'selected':''}`} fill={l?`url(#seat-${council}-${colorBy}-${l.id})`:'#ddd'} opacity={dim?.2:1} tabIndex={0} role="button" aria-label={`Seat ${s.seatId}: ${s.member?.name||'Vacant'}, ${s.member?.partyAbbreviation||''}, ${s.member?.canton||''}`} aria-pressed={active} onPointerEnter={()=>!selected&&setHovered(s)} onPointerLeave={()=>setHovered(null)} onFocus={()=>setHovered(s)} onBlur={()=>setHovered(null)} onClick={()=>{if(!moved.current)choose(s);}} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();choose(s);}if(e.key==='Escape'){setSelected(null);setView([0,0,860,565]);}}}><title>{s.member?.name} · Seat {s.seatId} · {s.member?.partyAbbreviation}</title></path>;})}
 </svg><p className="map-caption">Official desk positions · {colorBy==='party'?'Party colours with distinguishing patterns':'Official parliamentary-group colours'} · presidency counted once</p></div>
 <aside className="seat-inspector" aria-live="polite">{member?<>{member.portraitUrl&&<img src={member.portraitUrl} alt={member.name} onError={e=>e.currentTarget.hidden=true}/>}<p className="eyebrow">Seat {(selected||hovered).seatId} · {member.canton}</p><h3>{member.name}</h3><dl><dt>Party / organisation</dt><dd>{member.party}</dd><dt>Parliamentary group</dt><dd>{member.group}</dd></dl>{selected&&<><button className="primary" onClick={()=>onProfile(member.id)}>Open profile ↗</button><FollowButton user={user} kind="person" id={member.id} title={member.name} onAccount={onAccount}/><button className="text-button" onClick={()=>onAsk({kind:'person',id:member.id,title:member.name},{prompt:'What has '+member.name+' said in the imported debates?'})}>Ask about this member →</button><button className="text-button" onClick={()=>{setSelected(null);setView([0,0,860,565]);}}>Close selection</button></>}</>:<><span className="seat-outline">⌑</span><h3>Who sits here?</h3><p>Hover, focus or select a desk to see who sits there. Open their profile to explore their words and recorded votes.</p></>}</aside></div>
 <div className="chamber-legend" aria-label={`${colorBy} seat totals`}>{legend.map(l=><button key={l.id} aria-pressed={highlight===l.id} title={l.name} onClick={()=>setHighlight(highlight===l.id?null:l.id)}><span className={'party-swatch pattern-'+l.pattern} style={{backgroundColor:l.color}}/><span><strong>{l.abbreviation}</strong><small>{l.name}</small></span><b>{l.count}</b></button>)}</div>
 <details className="member-list"><summary>Find a member · accessible list ({snapshot.seats.length})</summary><input aria-label="Find a member, canton or seat" placeholder="Name, party, canton or seat…" value={query} onChange={e=>setQuery(e.target.value)}/><div>{filtered.map(s=><button key={s.seatId} onClick={()=>choose(s)}><strong>{s.member?.name||'Vacant'}</strong><span>{s.member?.partyAbbreviation} · {s.member?.canton} · seat {s.seatId}</span></button>)}</div></details>
 <div className="broadcast-link"><strong>Official broadcast</strong><span>{broadcast?.state==='live'?'Verified live':'Live status not verified'}</span><a href="https://www.parlament.ch/en/ratsbetrieb/amtliches-bulletin/amtliches-bulletin-videos" target="_blank" rel="noreferrer">Open Parliament’s video service ↗</a></div>
 <div className="snapshot-source"><a href={snapshot.officialPlanUrl} target="_blank" rel="noreferrer">View official seating plan ↗</a><details><summary>Snapshot sources & verification</summary><p>{snapshot.dateBasis} {snapshot.colorBasis}</p><p>Version {snapshot.version}. Seat shapes and stable member IDs reconciled against the official live service. Later changes create a new snapshot.</p>{snapshot.sources.map((s,i)=><p key={i}><a href={s.url} target="_blank" rel="noreferrer">{new URL(s.url).pathname}</a> · {s.retrievedAt.slice(0,10)}</p>)}</details></div></>}
 </section>;
}
