import React,{useEffect,useRef,useState} from 'react';
import {X,ArrowLeft,Play,UserCircle} from '@phosphor-icons/react';
import {pilotApi as api} from '../services/pilotApi.js';
import {cantonName} from './cantons.js';
import './citation-inspector.css';

const clock=value=>Number.isFinite(value)?`${Math.floor(value/60)}:${String(Math.floor(value%60)).padStart(2,'0')}`:'—';
export default function CitationInspector({source,quote,language,onClose,onFollowUp}){
 const fr=language==='fr',t=(en,frText)=>fr?frText:en;
 const [data,setData]=useState(null),[error,setError]=useState(''),[photoFailed,setPhotoFailed]=useState(false),[profile,setProfile]=useState(false);
 const close=useRef(null),player=useRef(null);
 useEffect(()=>{const previous=document.activeElement;close.current?.focus();return()=>previous?.focus();},[]);
 useEffect(()=>{let active=true;setData(null);setError('');setPhotoFailed(false);setProfile(false);if(source?.transcriptId)api.passageContext(source.id).then(d=>{if(active)setData(d);}).catch(()=>{if(active)setError(t('Surrounding text could not be loaded. The cited passage is still available.','Le contexte n’a pas pu être chargé. L’extrait cité reste disponible.'));});return()=>{active=false;};},[source?.id,language]);
 const selected=data?.passages.find(p=>p.id===source.id)||source,person=data?.person,video=selected?.video;
 const date=source?.date?new Date(source.date).toLocaleDateString(fr?'fr-CH':'en-GB',{day:'numeric',month:'long',year:'numeric'}):'';
 function follow(kind){onFollowUp({prompt:kind==='profile'?t(`Who is ${source.speaker}? Tell me about their official background.`,`Qui est ${source.speaker} ? Présente son parcours officiel.`):t(`Explain what ${source.speaker} is saying in this passage.`,`Explique ce que dit ${source.speaker} dans cet extrait.`),scope:{kind:'person',id:source.personId,title:source.speaker,passageId:kind==='profile'?undefined:source.id}});}
 return <div className="citation-layer" onKeyDown={e=>{if(e.key==='Escape'){e.stopPropagation();onClose();}}}>
 <button className="citation-backdrop" aria-label={t('Back to conversation','Retour à la conversation')} onClick={onClose}/>
 <section className="citation-inspector" role="dialog" aria-modal="true" aria-label={t('Source details','Détails de la source')} onKeyDown={e=>{if(e.key==='Tab'){const items=[...e.currentTarget.querySelectorAll('button:not(:disabled),a[href],video[controls],summary')].filter(el=>el.getClientRects().length);if(e.shiftKey&&document.activeElement===items[0]){e.preventDefault();items.at(-1)?.focus();}else if(!e.shiftKey&&document.activeElement===items.at(-1)){e.preventDefault();items[0]?.focus();}}}}>
 <header><button ref={close} onClick={onClose}><ArrowLeft/>{t('Conversation','Conversation')}</button><button onClick={onClose} aria-label={t('Close source','Fermer la source')}><X/></button></header>
 <div className="citation-body"><p className="eyebrow">{t('Behind the answer','À la source de la réponse')}</p>
 <div className="citation-person">{person?.portraitUrl&&!photoFailed?<img src={person.portraitUrl} alt={person.name} onError={()=>setPhotoFailed(true)}/>:<span className="citation-avatar"><UserCircle size={54}/></span>}<div><h2>{source?.speaker||t('Official source','Source officielle')}</h2><p>{date}{source?.council?` · ${source.council}`:''}</p>{person&&<small>{person.party||person.group} · {cantonName(person.canton,language)}{t(' · current profile',' · profil actuel')}</small>}</div></div>
 {data?.business&&<div className="citation-topic"><small>{data.business.number}</small><h3>{data.business.title}</h3></div>}
 <div className="citation-tabs" role="group" aria-label={t('Source sections','Sections de la source')}><button aria-pressed={!profile} onClick={()=>setProfile(false)}>{t('The passage','L’intervention')}</button>{person&&<button aria-pressed={profile} onClick={()=>setProfile(true)}>{t('About the speaker','À propos')}</button>}</div>
 {profile?<div className="citation-profile"><p>{person.council} · {person.party||person.group}</p>{person.joined&&<p>{t('Recorded term began','Début du mandat enregistré')} {person.joined.slice(0,10)}</p>}{person.occupations?.map((o,i)=><p key={i}>{o.title}{o.employer?` · ${o.employer}`:''}</p>)}<a href={person.officialUrl||person.sourceUrl} target="_blank" rel="noreferrer">{t('Official profile ↗','Profil officiel ↗')}</a>{person.portraitUrl&&<p><a href={person.portraitUrl} target="_blank" rel="noreferrer">{t('Portrait: Parliamentary Services ↗','Portrait : Services du Parlement ↗')}</a></p>}</div>:<>
 {video?.url?<div className="citation-video"><div><strong><Play size={15}/>{t('Cited extract','Extrait cité')} · {clock(video.start)}{Number.isFinite(video.end)?`–${clock(video.end)}`:''}</strong><button onClick={()=>{if(player.current){player.current.currentTime=video.start;player.current.play().catch(()=>{});}}}>{t('Replay extract','Revoir l’extrait')}</button></div><video ref={player} controls preload="metadata" src={video.url+'#t='+video.start} onLoadedMetadata={e=>{e.currentTarget.currentTime=video.start;}} onTimeUpdate={e=>{if(Number.isFinite(video.end)&&e.currentTarget.currentTime>=video.end&&!e.currentTarget.paused)e.currentTarget.pause();}}/><small>{video.reviewState?.includes('human')||selected.transcriptId?t('Machine-aligned timing · awaiting human review','Minutage automatique · vérification humaine à venir'):t('Publisher video extract','Extrait vidéo de l’éditeur')}</small></div>:<p className="citation-video-note">{t('An exact video extract is not available for this passage yet. You can read the original context below or open the official record.','Aucun extrait vidéo précisément minuté n’est encore disponible. Consultez le contexte original ci-dessous ou le compte rendu officiel.')}</p>}
 <div className="citation-original"><p className="eyebrow">{source?.language?.toUpperCase()} · {source?.transcriptId?t('Original text','Texte original'):t('Cited source text','Texte de la source citée')}</p>{source?.speakerFunction&&<small>{t('Recorded role','Rôle enregistré')}: {source.speakerFunction}</small>}<blockquote>{selected?.text||quote}</blockquote></div>
 {source?.transcriptId&&<section className="citation-context"><h3>{t('Around this passage','Autour de cet extrait')}</h3>{error?<p role="alert">{error}</p>:!data?<p role="status">{t('Loading context…','Chargement du contexte…')}</p>:<>{data.passages.filter(p=>p.id!==source.id).length?data.passages.map(p=>p.id===source.id?<p key={p.id} className="citation-position">{t('↑ Cited passage','↑ Extrait cité')}</p>:<p key={p.id}>{p.text}</p>):<p>{t('This is the only imported paragraph in this intervention.','C’est le seul paragraphe importé pour cette intervention.')}</p>}<small>{t('Adjacent paragraphs from the same official intervention.','Paragraphes voisins de la même intervention officielle.')}</small></>}</section>}
 <a className="citation-official" href={source?.officialUrl} target="_blank" rel="noreferrer">{source?.sourceKind==='party-self-description'?t('Open party source ↗','Source du parti ↗'):t('Open the official record ↗','Ouvrir le compte rendu officiel ↗')}</a>
 </>}
 </div>{source?.personId&&<footer><button onClick={()=>follow('passage')}>{t('Explain this passage','Expliquer cet extrait')}</button><button onClick={()=>follow('profile')}>{t('Ask about this person','En savoir plus sur cette personne')}</button></footer>}
 </section></div>;
}

