import PassageVideo from './PassageVideo.jsx';
import React,{useEffect,useRef,useState} from 'react';
import {ArrowUpRight,ArrowUp,ArrowsOutSimple,ArrowsInSimple,X,BookOpen,ClockCounterClockwise,Plus,Trash} from '@phosphor-icons/react';
import {pilotApi as api} from '../services/pilotApi.js';
import {newConversation,loadConversations,saveConversations,appendMessage} from './chat-history.mjs';
import CitationInspector from './CitationInspector.jsx';
import CleisthenesAnswer,{citationPassage,ResearchSummary} from './CleisthenesAnswer.jsx';
import './cleisthenes.css';
import './cleisthenes-refinement.css';

export default function Cleisthenes({language,expanded,onExpand,onCollapse,context,openRequest,user}){
 const fr=language==='fr',t=(en,frText)=>fr?frText:en;
 const [chats,setChats]=useState(()=>{const saved=loadConversations(localStorage);return saved.length?saved:[newConversation()];});
 const [activeId,setActiveId]=useState(()=>{try{return localStorage.getItem('swiss-pilot-active-chat')||chats[0].id;}catch{return chats[0].id;}}),[open,setOpen]=useState(false),[question,setQuestion]=useState(''),[pending,setPending]=useState(null),[progress,setProgress]=useState('sources'),[historyOpen,setHistoryOpen]=useState(false),[source,setSource]=useState(null),[storageOk,setStorageOk]=useState(true),[action,setAction]=useState('explain');
 const [retrySync,setRetrySync]=useState(0),[stages,setStages]=useState([]);
 const [cloudOwner,setCloudOwner]=useState(null),[cloudReady,setCloudReady]=useState(false),[syncNote,setSyncNote]=useState(''),[imported,setImported]=useState(false);
 const synced=useRef(new Map()),writes=useRef(new Map()),ownerRef=useRef(user?.id||null);ownerRef.current=user?.id||null;
 const ready=!user||cloudReady&&cloudOwner===user.id;
 const input=useRef(null),bottom=useRef(null),launcher=useRef(null),sending=useRef(false);
 const chat=chats.find(c=>c.id===activeId)||chats[0],messages=chat?.messages||[],scope=chat?.scope,busy=pending===chat?.id;
 useEffect(()=>{let live=true;setCloudReady(false);setCloudOwner(user?.id||null);synced.current=new Map();setSyncNote('');setImported(false);if(!user){const local=loadConversations(localStorage);setChats(local.length?local:[newConversation()]);setActiveId(local[0]?.id||null);setCloudReady(true);return;}setChats([newConversation()]);api.items('conversation').then(rows=>{if(!live)return;const list=rows.map(x=>x.payload).filter(c=>typeof c.id==='string'&&Array.isArray(c.messages)).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt));synced.current=new Map(list.map(c=>[c.id,JSON.stringify(c)]));setChats(list.length?list:[newConversation()]);setActiveId(list[0]?.id||null);setCloudReady(true);setSyncNote('Conversations synced to your account.');}).catch(()=>live&&setSyncNote('Account history could not load. Reload to retry; local chats have not been imported.'));return()=>{live=false;};},[user?.id]);
 useEffect(()=>{if(!user){if(cloudOwner===null)setStorageOk(saveConversations(localStorage,chats));return;}if(!ready)return;const owner=user.id;const timer=setTimeout(()=>{for(const c of chats.filter(c=>c.messages.length)){const value=JSON.stringify(c);if(synced.current.get(c.id)===value)continue;synced.current.set(c.id,value);const queue=writes.current.get(c.id)||Promise.resolve();const next=queue.catch(()=>{}).then(()=>{if(ownerRef.current!==owner)return;return api.putItem('conversation',c.id,c,owner);}).then(()=>{if(ownerRef.current===owner)setSyncNote('Conversations synced to your account.');}).catch(()=>{if(ownerRef.current===owner){synced.current.delete(c.id);setSyncNote('Sync failed. This conversation is only in this open window. Retry syncing before leaving.');}});writes.current.set(c.id,next);}},450);return()=>clearTimeout(timer);},[chats,user?.id,ready,cloudOwner,retrySync]);
 useEffect(()=>{const openExisting=e=>{setActiveId(e.detail);setOpen(true);setHistoryOpen(false);};addEventListener('open-conversation',openExisting);return()=>removeEventListener('open-conversation',openExisting);},[]);
 async function importLocal(){if(!user||!ready)return;const owner=user.id,local=loadConversations(localStorage);setSyncNote('Importing your chosen local history…');try{for(const c of local){if(ownerRef.current!==owner)return;if(!synced.current.has(c.id))await api.putItem('conversation',c.id,c,owner);}if(ownerRef.current!==owner)return;const rows=await api.items('conversation');if(ownerRef.current!==owner)return;const list=rows.map(r=>r.payload);synced.current=new Map(list.map(c=>[c.id,JSON.stringify(c)]));setChats(list.length?list:[newConversation()]);setImported(true);setSyncNote('Local history imported. The original browser copy is unchanged.');}catch{setSyncNote('Import did not finish. You can retry safely.');}}

 useEffect(()=>{try{localStorage.setItem('swiss-pilot-active-chat',chat.id);}catch{setStorageOk(false);}},[chat?.id]);
 // Navigation and language changes must not clear an existing conversation.
 useEffect(()=>{if(!openRequest||!ready)return;setOpen(true);setHistoryOpen(false);setQuestion(openRequest.prompt||'');setAction(openRequest.action||'explain');
  const same=chat?.scope?.id===context?.id&&chat?.scope?.kind===context?.kind&&chat?.scope?.passageId===context?.passageId;
  if(!same){const next=newConversation(context||null);setChats(c=>[next,...c].slice(0,20));setActiveId(next.id);}
  requestAnimationFrame(()=>input.current?.focus());
 },[openRequest,ready]);
 useEffect(()=>{if(open||expanded)input.current?.focus();},[open,expanded]);
 useEffect(()=>{bottom.current?.scrollIntoView({block:'nearest',behavior:'smooth'});},[messages.length,busy]);
 useEffect(()=>{if(!busy){setProgress('sources');return;}const timer=setTimeout(()=>setProgress('answer'),1200);return()=>clearTimeout(timer);},[busy]);
 useEffect(()=>{if(!input.current)return;input.current.style.height='auto';input.current.style.height=Math.min(input.current.scrollHeight,120)+'px';},[question]);
 function start(scopeOverride=context){if(!ready)return;const next=newConversation(scopeOverride||null);setChats(c=>[next,...c].slice(0,20));setActiveId(next.id);setQuestion('');setSource(null);setHistoryOpen(false);setAction('explain');setOpen(true);requestAnimationFrame(()=>input.current?.focus());}
 async function remove(id){if(user){const owner=user.id;try{await (writes.current.get(id)||Promise.resolve());if(ownerRef.current!==owner)return;await api.deleteItem('conversation',id,owner);synced.current.delete(id);}catch{setSyncNote('Could not delete the account conversation.');return;}}setChats(c=>{const rest=c.filter(row=>row.id!==id);return rest.length?rest:[newConversation()];});if(chat.id===id){setActiveId(chats.find(c=>c.id!==id)?.id||null);setQuestion('');}}
 async function send(e,prompt,requestedAction=action,scopeOverride){
  e?.preventDefault();const q=(prompt||question).trim();if(!q||sending.current||!ready)return;const sendingOwner=ownerRef.current;
  const id=chat.id,selectedScope=scopeOverride===undefined?scope:scopeOverride;
  const previous=messages.filter(m=>m.role==='assistant').at(-1);
  const conversation=previous?.scopeId===(selectedScope?.id||null)?previous?.answer?.context:undefined;
  sending.current=true;setPending(id);setStages([]);setQuestion('');setHistoryOpen(false);setChats(c=>appendMessage(c,id,{role:'user',text:q}));
  try{
   const answer=selectedScope?.kind==='search'?await api.discoverySearch({question:q,filters:selectedScope.filters,language}):selectedScope?.kind==='dossier'?await api.ask({dossierId:selectedScope.id,question:q,language,action:requestedAction}):await api.parliamentAskStream({question:q,language,context:conversation,scopeTitle:selectedScope?.title,...(selectedScope?{...(selectedScope.kind==='person'?{personId:selectedScope.id}:selectedScope.kind==='business'?{businessId:selectedScope.id}:{}),...(selectedScope.filters?{filters:selectedScope.filters}:{}),...(selectedScope.passageId?{passageId:selectedScope.passageId}:{})}:{})},event=>setStages(list=>[...list.filter(x=>x.stage!==event.stage),event]));
   if(selectedScope?.kind==='dossier'){const d=await api.dossier(selectedScope.id);answer.passages=d.evidence.map(e=>({id:e.id,evidenceId:e.id,speaker:e.attribution,text:e.text,language:e.language,sourceKind:e.sourceKind,officialUrl:e.source.url,date:d.date,...(e.kind==='video'?{video:{url:e.mediaUrl||e.videoUrl,start:e.start||0,end:e.end}}:{})}));}
   if(ownerRef.current!==sendingOwner)return;setChats(c=>appendMessage(c,id,{role:'assistant',answer,scopeId:selectedScope?.id||null}).map(row=>row.id===id&&row.scope?.passageId?{...row,scope:{...row.scope,passageId:undefined}}:row));
  }catch{if(ownerRef.current!==sendingOwner)return;setChats(c=>appendMessage(c,id,{role:'assistant',retry:q,retryAction:requestedAction,retryScope:selectedScope,error:t('I couldn’t reach the model. Your question is ready to retry.','Je n’ai pas pu joindre le modèle. Vous pouvez réessayer.')}));}
  finally{sending.current=false;setPending(null);setAction('explain');}
 }
 // A suggested follow-up continues the answer's debate, never a single passage.
 function askFollowUp(q,answer){const proposal=answer.researchSummary?.proposal,next=proposal?{kind:'business',id:proposal.id,title:proposal.title}:scope?{...scope,passageId:undefined}:null;setChats(c=>c.map(row=>row.id===chat.id?{...row,scope:next}:row));send(null,q,undefined,next);}
 function close(){setOpen(false);if(expanded)onCollapse();requestAnimationFrame(()=>launcher.current?.focus());}
 function followUp({prompt,scope:nextScope}){setSource(null);setChats(c=>c.map(row=>row.id===chat.id?{...row,scope:nextScope}:row));setQuestion(prompt);setHistoryOpen(false);requestAnimationFrame(()=>input.current?.focus());}
 const suggestions=scope?.kind==='dossier'?[[t('Compare arguments','Comparer les arguments'),t('What are the arguments for and against?','Quels sont les arguments pour et contre ?')],[t('Vote result','Résultat du vote'),t('What was the result of the vote?','Quel a été le résultat de la votation ?')]]:[[t('The 10-million initiative','L’initiative 10 millions'),t("What are the arguments for and against the initiative 'No to a Switzerland of 10 million'?","Quels sont les arguments pour et contre l'initiative « Pas de Suisse à 10 millions » ?")],[t('Stop blackout initiative','Initiative Stop au blackout'),t("What arguments were made in Parliament about the 'Stop blackout' initiative?","Quels arguments ont été avancés au Parlement sur l'initiative « Stop au blackout » ?")],[t('Crans-Montana victims law','Loi pour les victimes de Crans-Montana'),t('What did speakers say about the law supporting the victims of the Crans-Montana fire?','Qu’ont dit les orateurs sur la loi de soutien aux victimes de l’incendie de Crans-Montana ?')]];
 return <>
 {!(open||expanded)&&<button ref={launcher} className="cleisthenes-launcher" onClick={()=>setOpen(true)} aria-label={t('Chat with Cleisthenes','Discuter avec Cleisthenes')} aria-expanded={false}><img src={import.meta.env.BASE_URL+'brand/cleisthenes-bust.png'} alt=""/><span>Cleisthenes<small>{t('Let’s understand together','Comprenons ensemble')}</small></span><span className="cleisthenes-dot"/></button>}
 {(open||expanded)&&<section className={`cleisthenes-chat ${expanded?'expanded':''}`} role={expanded?'region':'dialog'} aria-label="Cleisthenes" onKeyDown={e=>{if(e.key==='Escape')close();}}>
 <header><img src={import.meta.env.BASE_URL+'brand/cleisthenes-bust.png'} alt=""/><div><strong>Cleisthenes</strong><small>{t('Your Swiss civic companion','Votre compagnon civique suisse')}</small></div><button aria-label={t('Recent chats','Discussions récentes')} title={t('Recent chats','Discussions récentes')} aria-pressed={historyOpen} onClick={()=>setHistoryOpen(v=>!v)}><ClockCounterClockwise/></button><button aria-label={t('New chat','Nouvelle discussion')} title={t('New chat','Nouvelle discussion')} onClick={()=>start()}><Plus/></button><button aria-label={expanded?t('Compact chat','Réduire'):t('Expand chat','Agrandir')} onClick={()=>{setOpen(true);expanded?onCollapse():onExpand();}}>{expanded?<ArrowsInSimple/>:<ArrowsOutSimple/>}</button><button aria-label={t('Close chat','Fermer')} onClick={close}><X/></button></header>
 {user&&<div className="sync-status" role="status">{syncNote||'Loading account conversations…'}{syncNote.startsWith('Sync failed')&&<button onClick={()=>setRetrySync(n=>n+1)}>Retry sync</button>}</div>}
 {user&&ready&&!imported&&loadConversations(localStorage).length>0&&<div className="chat-import">Existing chats are saved in this browser.<button onClick={importLocal}>Import into my account</button></div>}
 <div className="cleisthenes-scope"><BookOpen size={14}/><span>{scope?scope.title:t('All imported parliamentary records','Tous les débats parlementaires importés')}{scope?.passageId?t(' · selected passage',' · extrait sélectionné'):''}</span>{scope&&<button onClick={()=>start(null)}>{t('New topic','Autre sujet')}</button>}</div>
 {historyOpen?<div className="cleisthenes-history"><h2>{t('Recent chats','Discussions récentes')}</h2><p>{user?'Synced to your account.':t('Saved on this device · up to 20 chats.','Enregistrées sur cet appareil · jusqu’à 20 discussions.')}</p>{chats.filter(c=>c.messages.length).map(c=><div key={c.id}><button onClick={()=>{setActiveId(c.id);setQuestion('');setHistoryOpen(false);}} aria-current={c.id===chat.id?'true':undefined}><strong>{c.messages.find(m=>m.role==='user')?.text||t('Conversation','Discussion')}</strong><small>{new Date(c.updatedAt).toLocaleDateString(fr?'fr-CH':'en-GB')} · {c.messages.filter(m=>m.role==='user').length} {t('questions','questions')}</small></button><button disabled={pending===c.id} onClick={()=>remove(c.id)} aria-label={t('Delete chat: ','Supprimer la discussion : ')+(c.messages.find(m=>m.role==='user')?.text||'')}><Trash/></button></div>)}{!chats.some(c=>c.messages.length)&&<p>{t('Your conversations will appear here.','Vos discussions apparaîtront ici.')}</p>}<button className="chat-return" onClick={()=>setHistoryOpen(false)}>{t('Back to conversation','Retour à la conversation')}</button></div>:<div className="cleisthenes-messages" aria-live="polite">
 {!messages.length&&<div className="cleisthenes-welcome"><img src={import.meta.env.BASE_URL+'brand/cleisthenes-bust.png'} alt=""/><h2>{t('What’s on your mind?','Qu’aimeriez-vous comprendre ?')}</h2><p>{t('A question about Swiss politics. A source to explore.','Une question sur la politique suisse. Une source à explorer.')}</p><div className="cleisthenes-suggestions">{suggestions.map(([label,prompt])=><button key={label} title={prompt} onClick={()=>{setQuestion(prompt);input.current?.focus();}}>{label}<ArrowUpRight size={14}/></button>)}</div></div>}
 {messages.map((m,i)=><article key={i} className={'cleisthenes-message '+m.role}>{m.role==='user'?<p>{m.text}</p>:m.error?<div role="alert"><p>{m.error}</p><button disabled={!!pending} onClick={()=>send(null,m.retry,m.retryAction,m.retryScope)}>{t('Try again','Réessayer')}</button></div>:<>
 {m.answer.mode==='recorded-replay'&&<small>{t('Recorded demo','Démo enregistrée')}</small>}
 {m.answer.mode==='catalog-search'?<div><p>{m.answer.total} matching imported records. Your filters are preserved.</p>{m.answer.records.map(r=><p key={r.type+r.id}><a href={r.href} onClick={e=>{e.preventDefault();window.dispatchEvent(new CustomEvent('civic-navigate',{detail:r.href}));}}>{r.title} ↗</a><small> · {r.type} · {r.date}</small></p>)}<small>{m.answer.coverage}</small></div>:m.answer.answer?.lead?<CleisthenesAnswer answer={m.answer} language={language} disabled={!!pending} onCite={c=>setSource({source:citationPassage(m.answer,c),quote:c.quote})} onFollowUp={q=>askFollowUp(q,m.answer)}/>:m.answer.claims?.length?m.answer.claims.slice(0,3).map((c,j)=>{const s=m.answer.passages?.find(p=>p.evidenceId===c.evidenceId||'parl-'+p.id===c.evidenceId);return <div className="cleisthenes-point" key={j}><p>{c.text}</p>{s&&<button className="chat-citation" onClick={()=>setSource({source:s,quote:c.quote})}><BookOpen size={14}/><span>{s.speaker||t('Source','Source')}<small>{s.date?.slice(0,10)}{s.video?.url?t(' · video extract',' · extrait vidéo'):t(' · read context',' · lire le contexte')}</small></span><ArrowUpRight size={14}/></button>}{s?.transcriptId&&<PassageVideo source={s} language={language}/>}</div>;}):m.answer.status==='sources-only'?<div className="source-fallback"><p>{t('I found relevant official passages, but the AI answer could not be safely completed. You can still inspect the sources.','J’ai trouvé des extraits officiels pertinents, mais la réponse IA n’a pas pu être finalisée de manière sûre. Vous pouvez consulter les sources.')}</p>{m.answer.passages?.map((s,j)=><button key={s.id||j} className="chat-citation" onClick={()=>setSource({source:s,quote:s.text})}><BookOpen size={14}/><span>{s.speaker||t('Official source','Source officielle')}<small>{s.date?.slice(0,10)} · {t('read passage','lire l’extrait')}</small></span><ArrowUpRight size={14}/></button>)}</div>:m.answer.status==='refused'?<div className="answer-refusal"><p>{t('I don’t tell anyone how to vote or predict results — that decision is yours. What I can do is show you what each side argued in Parliament, with the original sources.','Je ne dis à personne comment voter et je ne prédis pas de résultats : cette décision vous appartient. Je peux en revanche vous montrer ce que chaque camp a défendu au Parlement, sources à l’appui.')}</p>{m.answer.suggestedFollowUps?.map(q=><button key={q} type="button" disabled={!!pending} onClick={()=>send(null,q)}>{q}<ArrowUpRight size={13}/></button>)}</div>:<p>{m.answer.status==='provider-unavailable'?t('The answer service is unavailable. You can still browse the original texts.','Le service de réponse est indisponible. Les textes originaux restent accessibles.'):t('I don’t have enough imported evidence for this question in this selection. Try a new topic or another source.','Je n’ai pas assez de sources importées pour cette question. Essayez un autre sujet ou une autre source.')}</p>}
 {!m.answer.answer&&m.answer.researchSummary&&['insufficient-evidence','sources-only'].includes(m.answer.status)&&<ResearchSummary summary={m.answer.researchSummary} t={t}/>}
 </>}</article>)}{busy&&stages.length>0&&<ResearchStages stages={stages} t={t}/>}{busy&&!stages.length&&<div className="cleisthenes-thinking" role="status"><span/><span/><span/>{progress==='sources'?t('Finding official sources…','Recherche des sources officielles…'):t('Writing a cited answer…','Rédaction d’une réponse sourcée…')}</div>}<div ref={bottom}/></div>}
 {!historyOpen&&<form className="cleisthenes-composer" onSubmit={send}><label className="sr-only" htmlFor="cleisthenes-question">{t('Ask Cleisthenes','Interroger Cleisthenes')}</label><textarea ref={input} id="cleisthenes-question" value={question} maxLength={500} rows={1} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send(e);}}} placeholder={t('Ask about the imported parliamentary record…','Posez une question sur les débats importés…')}/><button disabled={!!pending||!question.trim()||!ready} aria-label={t('Send question','Envoyer la question')}><ArrowUp/></button></form>}
 <footer>{user?'AI can be wrong. Check the sources. Questions are processed by the server; new chats sync to your account.':storageOk?t('AI can be wrong. Check the sources. Questions are processed by the server; chat history stays on this device.','L’IA peut se tromper. Vérifiez les sources. Les questions sont traitées par le serveur ; l’historique reste sur cet appareil.'):t('Device storage unavailable; this chat will not survive a reload.','Stockage indisponible ; cette discussion sera perdue au rechargement.')}</footer>
 </section>}
 {source&&<CitationInspector {...source} language={language} onClose={()=>setSource(null)} onFollowUp={followUp}/>}
 </>;
}

const STAGE_ORDER=['understanding','searching','reading','checking','writing'];
// Operational progress only: what is being searched and checked, never model reasoning.
function ResearchStages({stages,t}){
 const seen=new Map(stages.map(s=>[s.stage,s])),latest=STAGE_ORDER.filter(s=>seen.has(s)).at(-1);
 const label=s=>{const e=seen.get(s)||{};
  if(s==='understanding')return t('Understanding your question','Compréhension de la question');
  if(s==='searching')return e.sessions?t(`Searching ${e.sessions} parliamentary sessions in French, German and Italian`,`Recherche dans ${e.sessions} sessions parlementaires en français, allemand et italien`):t('Searching the official record','Recherche dans les archives officielles');
  if(s==='reading')return e.passages?t(`Reading the ${e.passages} most relevant of ${e.candidates||e.passages} passages`,`Lecture des ${e.passages} extraits les plus pertinents sur ${e.candidates||e.passages}`):t('Reading passages','Lecture des extraits');
  if(s==='checking')return e.claims?t(`Checking ${e.claims} statements against their sources`,`Vérification de ${e.claims} affirmations auprès des sources`):t('Checking statements against sources','Vérification auprès des sources');
  return t('Writing a cited answer','Rédaction d’une réponse sourcée');};
 return <ol className="cleisthenes-stages" role="status" aria-live="polite">{STAGE_ORDER.map(s=><li key={s} data-state={s===latest?'active':seen.has(s)?'done':'pending'}><span className="stage-dot"/>{label(s)}</li>)}</ol>;
}
