import React,{useEffect,useRef,useState} from 'react';
import {ArrowUpRight,ArrowUp,ArrowsOutSimple,ArrowsInSimple,X,BookOpen} from '@phosphor-icons/react';
import {pilotApi as api} from '../services/pilotApi.js';
import './cleisthenes.css';

export default function Cleisthenes({language,expanded,onExpand,onCollapse,context,openRequest}){
 const fr=language==='fr',t=(en,frText)=>fr?frText:en;
 const [open,setOpen]=useState(false),[question,setQuestion]=useState(''),[messages,setMessages]=useState([]),[busy,setBusy]=useState(false),[all,setAll]=useState(false);
 const input=useRef(null),bottom=useRef(null),launcher=useRef(null),request=useRef(0);
 useEffect(()=>{request.current++;setMessages([]);setBusy(false);},[context?.id,context?.kind,language]);
 const [action,setAction]=useState('explain');
 useEffect(()=>{if(!openRequest)return;setOpen(true);setAll(false);setQuestion(openRequest.prompt||'');setAction(openRequest.action||'explain');requestAnimationFrame(()=>input.current?.focus());},[openRequest]);
 useEffect(()=>{setAll(false);},[context?.id]);
 useEffect(()=>{if(open||expanded)input.current?.focus();},[open,expanded]);
 useEffect(()=>{bottom.current?.scrollIntoView({block:'nearest',behavior:'smooth'});},[messages,busy]);
 const scope=all?null:context;
 async function send(e,prompt,requestedAction=action){e?.preventDefault();const q=(prompt||question).trim();if(!q||busy)return;const rid=++request.current;setQuestion('');setMessages(m=>[...m,{role:'user',text:q}]);setBusy(true);
  try{const previous=messages.filter(m=>m.role==='assistant').at(-1);const conversation=previous?.scopeId===(scope?.id||null)?previous?.answer?.context:undefined;
   const answer=scope?.kind==='dossier'?await api.ask({dossierId:scope.id,question:q,language,action:requestedAction}):await api.parliamentAsk({question:q,language,context:conversation,...(scope?{[scope.kind==='person'?'personId':'businessId']:scope.id}:{})});
   if(scope?.kind==='dossier'){const d=await api.dossier(scope.id);answer.passages=d.evidence.map(e=>({id:e.id,evidenceId:e.id,speaker:e.attribution,officialUrl:e.source.url,date:d.date,...(e.kind==='video'?{video:{url:e.mediaUrl||e.videoUrl,start:e.start||0}}:{})}));}
   if(rid===request.current)setMessages(m=>[...m,{role:'assistant',answer,scopeId:scope?.id||null,scope:scope?.title||t('Parliament collection','Collection parlementaire')}]);
  }catch{if(rid===request.current)setMessages(m=>[...m,{role:'assistant',retry:q,retryAction:requestedAction,error:t('I couldn’t reach the model. Your question is ready to retry.','Je n’ai pas pu joindre le modèle. Vous pouvez réessayer sans ressaisir votre question.')}]);}finally{if(rid===request.current){setBusy(false);setAction('explain');}}
 }
 function close(){setOpen(false);if(expanded)onCollapse();launcher.current?.focus();}
 const suggestions=scope?.kind==='dossier'?(fr?['Quels sont les arguments pour et contre ?','Quel a été le résultat de la votation ?']:['What are the arguments for and against?','What was the result of the vote?']):(fr?['Que dit le débat sur la protection des données ?','Comment lutter contre la cybercriminalité ?']:['What does Parliament say about data protection?','What was discussed about cybercrime?']);
 return <><button ref={launcher} className="cleisthenes-launcher" onClick={()=>expanded?onCollapse():setOpen(v=>!v)} aria-label={t('Chat with Cleisthenes','Discuter avec Cleisthenes')} aria-expanded={open||expanded}><img src="/images/cleisthenes.png" alt=""/><span>Cleisthenes<small>{t('Let’s understand together','Comprenons ensemble')}</small></span>{open?<X size={18}/>:<span className="cleisthenes-dot"/>}</button>
 {(open||expanded)&&<section className={`cleisthenes-chat ${expanded?'expanded':''}`} role={expanded?'region':'dialog'} aria-label="Cleisthenes" onKeyDown={e=>{if(e.key==='Escape')close();}}><header><img src="/images/cleisthenes.png" alt=""/><div><strong>Cleisthenes</strong><small>{t('Your Swiss civic companion','Votre compagnon civique suisse')}</small></div><button title={expanded?t('Compact chat','Réduire'):t('Expand chat','Agrandir')} aria-label={expanded?t('Compact chat','Réduire'):t('Expand chat','Agrandir')} onClick={()=>{setOpen(true);expanded?onCollapse():onExpand();}}>{expanded?<ArrowsInSimple/>:<ArrowsOutSimple/>}</button><button aria-label={t('Close chat','Fermer')} onClick={close}><X/></button></header>
 <div className="cleisthenes-scope"><BookOpen size={14}/><span>{scope?.title||t('All imported parliamentary evidence','Toutes les sources parlementaires importées')}</span>{context&&<button disabled={busy} onClick={()=>setAll(v=>!v)}>{all?t('Use selection','Utiliser la sélection'):t('All sources','Toutes les sources')}</button>}</div>
 <div className="cleisthenes-messages" aria-live="polite">{!messages.length&&<div className="cleisthenes-welcome"><img src="/images/cleisthenes.png" alt={t('Cleisthenes, an illustrated Greek civic guide','Cleisthenes, un guide civique grec illustré')}/><p className="eyebrow">{t('A little clarity. A better question.','Un peu de clarté. Une meilleure question.')}</p><h2>{t('Democracy,\na conversation away.','La démocratie\ncommence par une question.')}</h2><p>{t('Ask in your language. We’ll explore the evidence, one question at a time.','Posez votre question dans votre langue. Explorons les sources, une question à la fois.')}</p><div className="cleisthenes-suggestions">{suggestions.map(q=><button key={q} onClick={()=>send(null,q)}>{q}<ArrowUpRight/></button>)}</div></div>}
 {messages.map((m,i)=><article key={i} className={'cleisthenes-message '+m.role}>{m.role==='user'?<p>{m.text}</p>:m.error?<div role="alert"><p>{m.error}</p>{m.retry&&<button className="secondary" disabled={busy} onClick={()=>send(null,m.retry,m.retryAction)}>{t('Try again','Réessayer')}</button>}</div>:<><small>{m.answer.mode==='live-inference'?t('NVIDIA · source-backed AI','NVIDIA · IA avec sources'):m.answer.mode==='recorded-replay'?t('Recorded demo','Démo enregistrée'):t('Evidence check','Vérification des sources')}{m.answer.cacheHit?' · '+t('cached answer','réponse en cache'):''}</small>{m.answer.claims?.length?m.answer.claims.slice(0,3).map((c,j)=>{const s=m.answer.passages?.find(s=>s.evidenceId===c.evidenceId||'parl-'+s.id===c.evidenceId);return <div className="cleisthenes-point" key={j}><p>{c.text}</p><details><summary><BookOpen size={13}/>{s?.speaker||t('Source','Source')} <span>{s?.date?.slice(0,10)}</span></summary>{s?.sourceKind&&<small>{s.sourceKind==='party-self-description'?t('Party self-description · reviewed summary','Présentation du parti · résumé vérifié'):t('Official structured record · normalized fields','Donnée officielle · champs normalisés')}</small>}<blockquote>{c.quote}</blockquote>{s&&<><a href={s.officialUrl} target="_blank" rel="noreferrer">{s.sourceKind==='party-self-description'?t('Open party source','Ouvrir la source du parti'):t('Open official source','Ouvrir la source officielle')} ↗</a>{s.video?.url&&<><small>{t('Official recording · machine-aligned passage','Enregistrement officiel · extrait aligné automatiquement')}</small><video controls preload="metadata" src={s.video.url+'#t='+s.video.start} onLoadedMetadata={e=>e.currentTarget.currentTime=s.video.start}/></>}</>}</details></div>;}):<p>{t('I don’t have enough imported evidence for this question in this selection. Try all sources, or choose a proposal with available passages.','Je n’ai pas assez de sources importées pour cette question dans cette sélection. Essayez toutes les sources ou un objet avec des extraits disponibles.')}</p>}</>}</article>)}
 {busy&&<div className="cleisthenes-thinking" role="status"><span/><span/><span/>{t('Reading the sources…','Lecture des sources…')}</div>}<div ref={bottom}/></div>
 <form className="cleisthenes-composer" onSubmit={send}><label className="sr-only" htmlFor="cleisthenes-question">{t('Ask Cleisthenes','Interroger Cleisthenes')}</label><input ref={input} id="cleisthenes-question" value={question} maxLength={500} onChange={e=>setQuestion(e.target.value)} placeholder={t('What would you like to understand?','Que souhaitez-vous comprendre ?')}/><button disabled={busy||!question.trim()} aria-label={t('Send question','Envoyer la question')}><ArrowUp/></button></form><footer>{t('AI can be wrong. Check the original sources. Text chat · voice comes next.','L’IA peut se tromper. Vérifiez les sources originales. Chat texte · voix à venir.')}</footer></section>}</>;
}
