import React,{useEffect,useState} from 'react';
import {pilotApi as api} from '../services/pilotApi.js';
import FollowButton from './FollowButton.jsx';
import {loadConversations} from './chat-history.mjs';
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Zurich',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const cantons='AG AI AR BE BL BS FR GE GL GR JU LU NE NW OW SG SH SO SZ TG TI UR VD VS ZG ZH'.split(' ');
export default function Dashboard({user,dossiers,onNavigate,onAsk,onAccount}){
 const [data,setData]=useState(null),[period,setPeriod]=useState('today'),[selected,setSelected]=useState(null),[day,setDay]=useState(null),[month,setMonth]=useState(today().slice(0,7)),[follows,setFollows]=useState([]),[following,setFollowing]=useState(false),[recent,setRecent]=useState([]),[canton,setCanton]=useState(''),[error,setError]=useState(''),[parties,setParties]=useState([]);
 useEffect(()=>{let live=true;const refresh=()=>api.dashboard().then(d=>live&&setData(d)).catch(()=>live&&setError('Dashboard unavailable. Please try again.'));refresh();const timer=setInterval(refresh,1800000);api.chamber('nr').then(s=>live&&setParties(s.parties)).catch(()=>{});return()=>{live=false;clearInterval(timer);};},[]);
 useEffect(()=>{let live=true;setFollows([]);setCanton('');const load=()=>{if(user){api.items('follow').then(r=>live&&setFollows(r.map(x=>({...x.payload,key:x.id})))).catch(()=>live&&setError('Could not load your follows.'));api.items('conversation').then(r=>live&&setRecent(r.map(x=>x.payload).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)).slice(0,3))).catch(()=>{});api.items('preference').then(r=>live&&setCanton(r.find(x=>x.id==='canton')?.payload.value||'')).catch(()=>{});}else setRecent(loadConversations(localStorage).slice(0,3));};load();addEventListener('follows-changed',load);return()=>{live=false;removeEventListener('follows-changed',load);};},[user?.id]);
 const events=[...(data?.agenda.events||[]),...dossiers.map(d=>({id:'vote-'+d.id,title:d.shortTitle.en,type:'popular-vote',date:d.date,status:'completed',dossierId:d.id,sourceUrl:'?issue='+d.id}))],date=today(),shown=events.filter(e=>day?e.date===day:period==='today'?(e.date===date||e.type==='session'&&e.date<=date&&e.endDate>=date):period==='upcoming'?e.date>date:e.date<date);if(period==='previous'&&!day)shown.reverse();
 const start=new Date(month+'-01T12:00:00Z'),offset=(start.getUTCDay()+6)%7,count=new Date(start.getUTCFullYear(),start.getUTCMonth()+1,0).getDate();
 const items=(data?.feed.items||[]).filter(i=>!following||follows.some(f=>f.kind==='business'&&f.id===i.businessId));
 return <section className="civic-dashboard"><div className="workspace-heading"><div><p className="eyebrow">Your civic workspace · Switzerland</p><h1>{user?.name?'Welcome, '+user.name+'.':'A view of public life.'}</h1><p>Follow the proceedings. Keep your sources close. Find your own perspective.</p></div><span className="today-stamp">{new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/Zurich',weekday:'long',day:'numeric',month:'long'}).format(new Date())}<small>Europe / Zurich</small></span></div>
 <div className="dashboard-shortcuts"><button onClick={()=>onNavigate(null,'parliament')}><span>Explore the chambers</span><strong>246 representatives ↗</strong></button><button onClick={()=>onNavigate(null,'explore')}><span>Understand a proposal</span><strong>Topics & votes ↗</strong></button><button onClick={()=>onAsk(null,{prompt:'What are the main issues in the latest imported parliamentary debates?'})}><span>A question on your mind?</span><strong>Ask Cleisthenes ↗</strong></button></div>
 {error&&<p role="status">{error}</p>}<div className="dashboard-grid"><section className="workspace-card proceedings"><div className="workspace-heading"><h2>In Parliament</h2><span className="status-tag">Official agenda</span></div><div className="workspace-segments">{['today','upcoming','previous'].map(p=><button key={p} aria-pressed={period===p&&!day} onClick={()=>{setPeriod(p);setDay(null);}}>{p[0].toUpperCase()+p.slice(1)}</button>)}</div>{day&&<p>{day} <button onClick={()=>setDay(null)}>Clear date ×</button></p>}{shown.slice(0,7).map(e=><button className="event-row" key={e.id} onClick={()=>setSelected(e)}><time><b>{e.date.slice(8)}</b>{new Date(e.date+'T12:00:00Z').toLocaleDateString('en-GB',{month:'short'})}</time><span><strong>{e.title}</strong><small>{e.type==='session'?e.date+' – '+e.endDate:e.time||e.date} · {e.type==='session'?'Scheduled session':e.type==='popular-vote'?'Completed popular vote':e.status==='completed'?'Completed debate':e.date<date?'Past sitting · completion unverified':'Scheduled sitting'}</small></span><span>↗</span></button>)}{!shown.length&&<p className="empty-state">{!data?'Loading the official agenda…':'No imported sittings for this selection. Check upcoming dates or the official agenda.'}</p>}<small>Refreshed {data?.agenda.retrievedAt?new Date(data.agenda.retrievedAt).toLocaleString('en-GB',{timeZone:'Europe/Zurich'}):'not yet'} · hourly{data?.agenda.stale?' · refresh unavailable; last snapshot shown':''}</small><p><a href="https://www.parlament.ch/en/ratsbetrieb/sessions/schedule" target="_blank" rel="noreferrer">Full official agenda ↗</a></p></section>
 <section className="workspace-card calendar"><div className="workspace-heading"><h2>Calendar</h2><input aria-label="Calendar month" type="month" value={month} onChange={e=>e.target.value&&setMonth(e.target.value)}/></div><div className="calendar-grid">{'M T W T F S S'.split(' ').map((x,i)=><small key={'day'+i}>{x}</small>)}{Array.from({length:offset},(_,i)=><span key={'blank'+i}/>)}{Array.from({length:count},(_,i)=>{const d=month+'-'+String(i+1).padStart(2,'0'),n=events.filter(e=>e.date===d).length;return <button key={d} className={n?'has-events':''} aria-label={`${d}, ${n} sittings`} aria-pressed={day===d} aria-current={date===d?'date':undefined} onClick={()=>setDay(d)}>{i+1}<i/></button>;})}</div><p className="muted">● Sittings, session openings & votes · Europe/Zurich</p>{selected&&<div className="event-inspector"><button className="text-button" onClick={()=>setSelected(null)}>Close ×</button><h3>{selected.title}</h3><p>{selected.date} · {selected.time} · Europe/Zurich</p><p>{selected.type==='popular-vote'?'Historical popular vote.':selected.type==='session'?'Session runs through '+selected.endDate+'. Individual sitting times appear when published.':selected.status==='completed'?'Imported debate available':'Scheduled agenda entry. This is not a live indicator.'}</p>{selected.dossierId?<button className="text-button" onClick={()=>onNavigate(selected.dossierId)}>Open dossier & official sources →</button>:<a href={selected.sourceUrl} target="_blank" rel="noreferrer">Official record ↗</a>}<button className="secondary" onClick={()=>selected.dossierId?onNavigate(selected.dossierId):onAsk({kind:'agenda',id:selected.id,title:selected.title,filters:{session:selected.sessionId,date:selected.date}},{prompt:'What was discussed in this sitting? Use only available imported passages.'})}>Ask about this sitting</button></div>}</section>
 <section className="workspace-card follows"><h2>Your follows</h2><p>Choose what you want to keep up with. These choices never imply a political affiliation.</p>{follows.map(f=><div className="followed-row" key={f.key}><span>{f.title}<small>{f.kind}</small></span><FollowButton user={user} kind={f.kind} id={f.id} title={f.title} onAccount={onAccount}/></div>)}{!follows.length&&<p className="muted">Follow a person in Parliament, or choose a topic or party below.</p>}<details><summary>Choose topics & parties</summary>{dossiers.map(d=><div className="followed-row" key={d.id}><span>{d.shortTitle.en}</span><FollowButton user={user} kind="topic" id={d.id} title={d.shortTitle.en} onAccount={onAccount}/></div>)}{parties.map(p=><div className="followed-row" key={p.id}><span>{p.abbreviation} · {p.name}</span><FollowButton user={user} kind="party" id={p.id} title={p.name} onAccount={onAccount}/></div>)}</details><label className="canton-choice">Canton (optional)<select value={canton} onChange={async e=>{if(!user){onAccount();return;}const value=e.target.value;try{await api.putItem('preference','canton',{value});setCanton(value);}catch{setError('Canton preference could not be saved.');}}}><option value="">All Switzerland</option>{cantons.map(c=><option key={c}>{c}</option>)}</select></label><small>Your canton is a preference, not proof of residence. Local feed coverage is not available yet.</small></section>
 <section className="workspace-card"><h2>Recent research</h2>{recent.length?recent.map(c=><button key={c.id} className="recent-research" onClick={()=>{onNavigate(null,'chat');window.dispatchEvent(new CustomEvent('open-conversation',{detail:c.id}));}}><strong>{c.messages.find(m=>m.role==='user')?.text||'Conversation'}</strong><small>{c.scope?.title||'Parliament'} · {new Date(c.updatedAt).toLocaleDateString('en-GB')}</small></button>):<p className="empty-state">Your conversations will appear here as you explore.</p>}<button className="secondary" onClick={()=>onNavigate(null,'saved')}>Open saved research →</button></section></div>
 <section className="news-section"><div className="workspace-heading"><div><p className="eyebrow">From the public record</p><h2>News & updates</h2></div><div className="workspace-segments"><button aria-pressed={!following} onClick={()=>setFollowing(false)}>All updates</button><button aria-pressed={following} onClick={()=>setFollowing(true)}>Following</button></div></div><p className="muted">{following?'Updates linked to proposals you explicitly follow. No matching update is inferred from political interests.':'Official proposal updates from the imported collection.'} {data?.feed.stale?'Source snapshot is more than 24 hours old.':''}</p><div className="updates-grid">{items.slice(0,6).map(i=><article key={i.id}><small>{i.publisher} · {i.date?.slice(0,10)}</small><h3>{i.title}</h3><p>{i.stage}</p><div className="member-actions"><a href={i.sourceUrl} target="_blank" rel="noreferrer">Original record ↗</a><button onClick={()=>onAsk({kind:'business',id:i.businessId,title:i.title},{prompt:'Explain this proposal using its available parliamentary sources.'})}>Ask Cleisthenes</button></div><FollowButton user={user} kind="business" id={i.businessId} title={i.title} onAccount={onAccount}/></article>)}</div>{!items.length&&<p>No matching updates in the current imported collection.</p>}<div className="publisher-links"><strong>Public-service reporting</strong>{data?.feed.publishers.map(p=><a key={p.id} href={p.url} target="_blank" rel="noreferrer">{p.name} ↗</a>)}<small>Read on the publisher’s site. Article syndication awaits verified reuse permission.</small></div></section>
 </section>;
}
