import React,{useEffect,useState} from 'react';
import {pilotApi as api} from '../services/pilotApi.js';
export default function Feedback(){
 const [check,setCheck]=useState(null),[message,setMessage]=useState(''),[email,setEmail]=useState(''),[answer,setAnswer]=useState(''),[website,setWebsite]=useState(''),[status,setStatus]=useState(''),[busy,setBusy]=useState(false);
 const refresh=()=>api.feedbackChallenge().then(setCheck).catch(()=>setCheck({available:false}));
 useEffect(()=>{refresh();},[]);
 async function send(e){e.preventDefault();setBusy(true);setStatus('');try{await api.feedback({message,email,answer,website,challenge:check.id});setStatus('Your feedback was accepted for delivery. Thank you.');setMessage('');setEmail('');}catch{setStatus('Your message was not sent. Please try again, or email contact@midnight.vote.');}finally{setAnswer('');setBusy(false);refresh();}}
 return <><h2>Send feedback</h2><p>What could work better? Your message goes to contact@midnight.vote. We do not attach your conversations or account details.</p>{check?.available?<form onSubmit={send}><label>Your message<textarea required minLength={10} maxLength={4000} rows={5} value={message} onChange={e=>setMessage(e.target.value)}/></label><label>Email for a reply (optional)<input type="email" maxLength={254} value={email} onChange={e=>setEmail(e.target.value)}/></label><label style={{position:'absolute',left:'-10000px'}} aria-hidden="true">Website<input tabIndex={-1} autoComplete="off" value={website} onChange={e=>setWebsite(e.target.value)}/></label><label>{check.question}<input required inputMode="numeric" autoComplete="off" value={answer} onChange={e=>setAnswer(e.target.value)}/></label><button className="primary" disabled={busy}>{busy?'Sending…':'Send feedback'}</button></form>:<p>{check?'In-app delivery is not connected yet. ': 'Checking delivery… '}{check&&<a href="mailto:contact@midnight.vote?subject=Swiss%20pilot%20feedback">Email contact@midnight.vote ↗</a>}</p>}<p role="status">{status}</p></>;
}
