import React,{useEffect,useState,useRef} from 'react';
import {pilotApi as api} from '../services/pilotApi.js';
import './parliament.css';
import PassageTranslation from './PassageTranslation.jsx';
import SessionCoverage from './SessionCoverage.jsx';
import VideoSearch from './VideoSearch.jsx';
import PoliticianProfile from './PoliticianProfile.jsx';

export default function ParliamentExplorer({language='en',onContext}){
 const fr=language==='fr';const label=(en,frText)=>fr?frText:en;
 const [data,setData]=useState(null),[tab,setTab]=useState('projects'),[filter,setFilter]=useState(''),[stage,setStage]=useState('current'),[detail,setDetail]=useState(null),[kind,setKind]=useState('business'),[query,setQuery]=useState('protection des données'),[passages,setPassages]=useState([]),[answer,setAnswer]=useState(null),[selected,setSelected]=useState([]),[comparison,setComparison]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const request=useRef(0);
 useEffect(()=>{let active=true;api.parliament().then(d=>active&&setData(d)).catch(()=>active&&setError('Unable to load parliamentary data.'));return()=>{active=false;request.current++;};},[]);
 const date=v=>v?new Date(v).toLocaleDateString(fr?'fr-CH':'en-GB'):'—';
 async function open(type,id){const n=++request.current;setBusy(true);setError('');setAnswer(null);setSelected([]);setComparison(null);setPassages([]);try{const d=await(type==='person'?api.parliamentPerson(id):api.parliamentBusiness(id));if(n!==request.current)return;setKind(type);setDetail(d);onContext?.({kind:type,id:d.id,title:d.name||d.title});setPassages((d.speeches||[]).slice(0,8));}catch{setError(label('Record unavailable.','Document indisponible.'));}finally{if(n===request.current)setBusy(false);}}
 async function ask(e){e.preventDefault();const n=++request.current;setBusy(true);setError('');setAnswer(null);try{const a=await api.parliamentAsk({question:query,language,...(detail?{[kind==='person'?'personId':'businessId']:detail.id}:{})});if(n!==request.current)return;setAnswer(a);setPassages(a.passages||[]);}catch{setError(label('The model is unavailable or returned an invalid answer. Please inspect the sources.','Le modèle est indisponible ou sa réponse est invalide. Consultez les sources.'));}finally{if(n===request.current)setBusy(false);}}
 async function search(e){e.preventDefault();setBusy(true);setError('');try{setPassages(await api.parliamentSearch(query));setAnswer(null);}catch{setError(label('Search unavailable.','Recherche indisponible.'));}finally{setBusy(false);}}
 async function compare(){setBusy(true);setError('');try{setComparison(await api.compareStatements({ids:selected,language}));}catch{setError(label('Comparison unavailable.','Comparaison indisponible.'));}finally{setBusy(false);}}
 if(!data)return <section className="parliament"><h1>{label('Parliament','Parlement')}</h1><p role="status">{error||label('Loading official records…','Chargement des données officielles…')}</p></section>;
 const rows=(tab==='people'?data.people:data.businesses).filter(r=>(tab==='people'||stage==='all'||(stage==='current'&&data.sessions?.some(s=>s.start?.slice(0,10)<=new Date().toISOString().slice(0,10)&&s.end?.slice(0,10)>=new Date().toISOString().slice(0,10)&&s.businessIds.includes(r.id)))||r.statusGroup===stage)&&`${r.name||r.title} ${r.canton||''} ${r.number||''} ${r.party||''}`.toLowerCase().includes(filter.toLowerCase()));
 const last=data.runs.find(r=>r.status==='complete');
 return <section className="parliament"><div className="parliament-heading"><p className="eyebrow">{label('The public record','Les archives publiques')}</p><h1>{label('Follow the decision.','Suivre la décision.')}</h1><p>{label('Discover proposals, read parliamentary words, and inspect individual votes.','Explorer les objets, lire les interventions et consulter les votes individuels.')}</p></div>
 <div className="parliament-coverage"><strong>{data.counts.business||0} {label('proposals','objets')} · {data.counts.vote||0} {label('proposal roll calls','scrutins des objets')} · {data.counts.speech||0} {label('text passages','extraits')}</strong><span>{label('Official snapshot','Données officielles consultées le')} {date(last?.sourceRetrievedAt||last?.finished)}</span><p>{label('Official records from imported sessions and proposals. Open session coverage to see what is searchable and what has been video-processed. This is a retrieved snapshot.','Données officielles des sessions et objets importés. Consultez la couverture pour distinguer les textes indexés des vidéos traitées.')}</p></div>
 <SessionCoverage sessions={data.sessions} language={language}/><VideoSearch key={language} language={language}/><div className="parliament-layout"><aside className="parliament-directory"><div className="tabs"><button aria-pressed={tab==='projects'} onClick={()=>{setTab('projects');setFilter('');}}>{label('Proposals','Objets')}</button><button aria-pressed={tab==='people'} onClick={()=>{setTab('people');setFilter('');}}>{label('People','Personnes')}</button></div><input aria-label={label('Filter records','Filtrer les documents')} placeholder={label('Name, canton or proposal…','Nom, canton ou objet…')} value={filter} onChange={e=>setFilter(e.target.value)}/>{tab==='projects'&&<select aria-label={label('Parliamentary stage','Étape parlementaire')} value={stage} onChange={e=>setStage(e.target.value)}><option value="current">{label('Current session · imported','Session actuelle · importée')}</option><option value="all">{label('All parliamentary stages','Toutes les étapes')}</option><option value="proceedings">{label('In proceedings','En cours')}</option><option value="concluded">{label('Concluded','Terminés')}</option><option value="unclassified">{label('Stage to review','Étape à vérifier')}</option></select>}<button className="parliament-feature" onClick={()=>open('business','20230073')}>{label('Explore the e-ID record →','Explorer le dossier e-ID →')}</button><div className="parliament-records">{rows.map(r=><button key={r.id} aria-pressed={detail?.id===r.id&&kind===(tab==='people'?'person':'business')} onClick={()=>open(tab==='people'?'person':'business',r.id)}><small>{r.number||r.canton||'CH'} · {tab==='people'?r.party||r.group:r.status}</small><strong>{r.name||r.title}</strong>{tab==='projects'&&<small>{r.passageCount||0} {label('passages available','extraits disponibles')}</small>}{r.modified&&<small>{label('Updated','Actualisé le')} {date(r.modified)}</small>}</button>)}{!rows.length&&<p>{label('No records in this imported collection.','Aucun document dans cette collection importée.')}</p>}</div></aside>
 <div className="parliament-workspace">{!detail?<div className="parliament-welcome"><h2>{label('A proposal has a history.','Chaque objet a une histoire.')}</h2><p>{label('Choose an object or a parliamentarian. Start with e-ID to explore original interventions and recorded decisions.','Choisissez un objet ou une personne. Le dossier e-ID relie les interventions originales aux décisions enregistrées.')}</p></div>:<article className="parliament-detail"><p className="eyebrow">{kind==='person'?label('Public representative','Représentant public'):detail.number}</p><h2>{detail.name||detail.title}</h2>{kind==='business'?<><p><strong>{label('Parliamentary status','État parlementaire')}:</strong> {detail.status} · {date(detail.statusDate)}</p><a href={detail.officialUrl} target="_blank" rel="noreferrer">{label('Open Curia Vista ↗','Consulter Curia Vista ↗')}</a>{detail.popularVote&&<p className="notice">{label('Separate popular vote: completed on','Votation populaire distincte : terminée le')} {date(detail.popularVote.date)} · {label('accepted','accepté')}. <a href={detail.popularVote.sourceUrl} target="_blank" rel="noreferrer">{label('Official result','Résultat officiel')}</a></p>}<details><summary>{label('Parliamentary timeline','Chronologie parlementaire')} ({detail.timeline.length})</summary><ol>{detail.timeline.map(e=><li key={e.id}><time>{date(e.date)}</time> — {e.label}</li>)}</ol>{!detail.timeline.length&&<p>{label('Timeline not imported.','Chronologie non importée.')}</p>}</details></>:<PoliticianProfile key={detail.id} person={detail} language={language} onUpdate={d=>{setDetail(current=>current?.id===d.id?d:current);setData(old=>({...old,people:old.people.map(p=>p.id===d.id?d:p)}));}}/>}
 {kind==='business'&&<details><summary>{label('Recorded votes','Votes enregistrés')} ({detail.votes.length})</summary>{detail.votes.map(v=><div className="parliament-vote" key={v.id}><strong>{date(v.date)} · {v.subject||v.billTitle||v.title||v.voteId}</strong>{kind==='person'&&<p>{label('Recorded decision','Décision enregistrée')}: {v.decisionText||label('Label unavailable','Libellé indisponible')} · {v.group}</p>}<p>{label('Yes means','Oui signifie')}: {v.meaningYes||'—'}<br/>{label('No means','Non signifie')}: {v.meaningNo||'—'}</p><a href={v.sourceUrl||v.officialUrl} target="_blank" rel="noreferrer">{label('Official record ↗','Donnée officielle ↗')}</a></div>)}{!detail.votes.length&&<p>{label('No vote history imported for this selection.','Aucun historique de votes importé pour cette sélection.')}</p>}</details>}</article>}
 <details className="parliament-ask-disclosure"><summary>{label('Ask Cleisthenes about this record','Interroger Cleisthenes sur ce dossier')}</summary><section className="ask-box"><h2>{label('Ask Cleisthenes','Interroger Cleisthenes')}</h2><p>{label('Ask in English, French, German or Italian. Cleisthenes searches across languages and links each point to its source.','Posez votre question en français, allemand, italien ou anglais. Cleisthenes recherche dans plusieurs langues et cite ses sources.')}</p><form onSubmit={ask}><input aria-label={label('Question','Question')} value={query} maxLength={500} onChange={e=>setQuery(e.target.value)} required/><button className="primary" disabled={busy}>{label('Ask AI','Interroger l’IA')}</button></form><button className="text-button" disabled={busy} onClick={search}>{label('Search all imported passages','Chercher dans tous les extraits importés')}</button>{busy&&<p role="status">{label('Working…','Traitement en cours…')}</p>}{error&&<p role="alert">{error}</p>}
 {answer&&<div className="answer"><small>{answer.mode==='live-inference'?label('Live NVIDIA inference · AI synthesis to verify','Inférence NVIDIA en direct · synthèse IA à vérifier'):answer.mode||answer.status}</small>{answer.claims?.length?answer.claims.map((c,i)=><p key={i}><strong>{answer.passages?.find(s=>'parl-'+s.id===c.evidenceId)?.speaker} · {date(answer.passages?.find(s=>'parl-'+s.id===c.evidenceId)?.date)}</strong><br/>{c.text} <a href={'#passage-'+c.evidenceId.replace(/^parl-/,'')}>[{i+1}]</a></p>):<p>{label('No supported answer is available from this selection.','Aucune réponse étayée disponible dans cette sélection.')}</p>}</div>}</section></details>
 <section><div className="section-heading"><h2>{label('Original passages','Extraits originaux')}</h2><button hidden className="secondary" disabled={selected.length!==2||busy} onClick={compare}>{label('Compare two passages','Comparer deux extraits')} ({selected.length}/2)</button></div><p hidden>{label('A comparison can identify questions to investigate. Speaker role, bill version and context must be reviewed before claiming a change of stance.','Une comparaison peut révéler des questions à examiner. Il faut vérifier le rôle, la version du projet et le contexte avant de conclure à un changement de position.')}</p>{comparison&&<div className="notice" role="status"><strong>{comparison.status}</strong><p>{comparison.explanation}</p>{comparison.limitations&&<p>{comparison.limitations}</p>}</div>}{passages.map(s=><article className="parliament-passage" id={'passage-'+s.id} key={s.id}><div className="evidence-meta"><span>{(s.language||'fr').toUpperCase()} · {label('Official Bulletin text','Texte du Bulletin officiel')}</span><span>{date(s.date)}</span></div><h3>{s.speaker}</h3><small>{s.council} · {label('Recorded role','Rôle enregistré')}: {s.speakerFunction||'—'}</small><blockquote>{s.text}</blockquote><PassageTranslation key={s.id+language} passage={s} language={language}/><div className="card-actions"><a href={s.officialUrl} target="_blank" rel="noreferrer">{label('Original source ↗','Source originale ↗')}</a><button hidden aria-pressed={selected.includes(s.id)} disabled={!selected.includes(s.id)&&selected.length===2} onClick={()=>{setComparison(null);setSelected(v=>v.includes(s.id)?v.filter(x=>x!==s.id):[...v,s.id]);}}>{selected.includes(s.id)?label('Selected','Sélectionné'):label('Select','Sélectionner')}</button></div>{s.video?<div><video controls preload="metadata" src={s.video.url+'#t='+s.video.start} onLoadedMetadata={e=>e.currentTarget.currentTime=s.video.start}/><small>{label('Official parliamentary recording · machine-aligned','Enregistrement parlementaire officiel · alignement automatique')} · {s.video.start.toFixed(1)}–{s.video.end.toFixed(1)}s</small></div>:<small>{label('Video timing has not been aligned.','Le minutage vidéo n’est pas encore aligné.')}</small>}</article>)}</section></div></div></section>;
}
