import React,{useState,useRef} from 'react';
import {pilotApi as api} from '../services/pilotApi.js';
const clock=n=>`${Math.floor(n/60)}:${String(Math.floor(n%60)).padStart(2,'0')}`;
export default function PassageVideo({source,language='en'}){
 const [recording,setRecording]=useState(null),[loading,setLoading]=useState(false),[failed,setFailed]=useState(false),requested=useRef(false),player=useRef(null),fr=language==='fr',v=recording?.clip||source.video;
 const exact=Boolean(v?.url&&Number.isFinite(v.start)&&Number.isFinite(v.end)&&v.end>v.start);
 async function opened(e){if(!e.currentTarget.open){player.current?.pause();return;}if(exact||requested.current)return;requested.current=true;setLoading(true);try{setRecording(await api.recording(source.id));}catch{setFailed(true);}finally{setLoading(false);}}
 return <details className="passage-video-disclosure" onToggle={opened}><summary>{fr?'Voir la vidéo':'Watch the video'}{exact?` · ${clock(v.start)}–${clock(v.end)}`:''}</summary>{loading?<p role="status">{fr?'Vérification de la vidéo officielle…':'Checking the official recording…'}</p>:exact||recording?.status==='available'?<><p><strong>{exact?(fr?'Extrait minuté':'Timed passage'):(fr?'Intervention complète':'Full intervention')}</strong> · {exact?(fr?'Alignement automatique, vérification humaine à venir.':'Machine-aligned; human timing review pending.'):(fr?'Le minutage exact de cette citation n’est pas encore vérifié.':'The exact quote timestamp is not yet verified.')}</p><video ref={player} controls preload="none" src={exact?v.url+'#t='+v.start:recording.url} onError={()=>setFailed(true)} onLoadedMetadata={e=>{if(exact)e.currentTarget.currentTime=v.start;}} onTimeUpdate={e=>{if(exact&&e.currentTarget.currentTime>=v.end&&!e.currentTarget.paused)e.currentTarget.pause();}}/>{exact&&<button onClick={()=>{player.current.currentTime=v.start;player.current.play().catch(()=>{});}}>{fr?'Revoir cet extrait':'Replay this passage'}</button>}</>:<p>{fr?'Aucune vidéo officielle vérifiée n’est disponible pour cette intervention.':'A verified official recording is not available for this intervention.'}</p>}{failed&&<p role="status">{fr?'La lecture est indisponible ici. Utilisez le compte rendu officiel.':'Playback is unavailable here. Open the official record below.'}</p>}<a href={source.officialUrl} target="_blank" rel="noreferrer">{fr?'Compte rendu officiel ↗':'Official record ↗'}</a></details>;
}
