import React,{useEffect,useRef,useState} from 'react';
import {pilotApi as api} from '../services/pilotApi.js';
export default function PassageTranslation({passage,language}){
 const fr=language==='fr',t=(a,b)=>fr?b:a;
 const [target,setTarget]=useState(['en','fr','de','it'].includes(language)?language:'en'),[result,setResult]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[speaking,setSpeaking]=useState(false);
 const generation=useRef(0),utterance=useRef(null);
 function stop(){if(utterance.current){window.speechSynthesis?.cancel();utterance.current=null;}setSpeaking(false);}
 useEffect(()=>{generation.current++;setResult(null);setError('');setBusy(false);stop();return()=>{generation.current++;if(utterance.current)window.speechSynthesis?.cancel();};},[target,passage.id]);
 async function translate(){const current=++generation.current;setBusy(true);setError('');try{const r=await api.translatePassage({evidenceId:passage.id,language:target});if(r.status!=='ok')throw Error();if(current===generation.current)setResult(r);}catch{if(current===generation.current)setError(t('Translation unavailable. The original remains available.','Traduction indisponible. Le texte original reste accessible.'));}finally{if(current===generation.current)setBusy(false);}}
 function listen(){stop();setError('');const synth=window.speechSynthesis,voice=synth?.getVoices().find(v=>v.lang.toLowerCase().startsWith(target));if(!voice){setError(t('No device voice is available for this language.','Aucune voix disponible sur cet appareil pour cette langue.'));return;}const u=new SpeechSynthesisUtterance(result.text);u.voice=voice;u.lang=voice.lang;u.onend=()=>{utterance.current=null;setSpeaking(false);};u.onerror=()=>{utterance.current=null;setSpeaking(false);setError(t('Audio playback unavailable.','Lecture audio indisponible.'));};utterance.current=u;setSpeaking(true);synth.speak(u);}
 return <div className="passage-translation" style={{margin:'16px 0'}}><div style={{display:'flex',flexWrap:'wrap',gap:8,alignItems:'center'}}><label>{t('Translate to','Traduire en')} <select aria-label={t('Translation language','Langue de traduction')} value={target} onChange={e=>setTarget(e.target.value)}>{[['en','English'],['fr','Français'],['de','Deutsch'],['it','Italiano']].map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><button type="button" className="secondary" disabled={busy||target===passage.language} onClick={translate}>{busy?t('Translating…','Traduction…'):target===passage.language?t('Original language','Langue originale'):t('Translate passage','Traduire l’extrait')}</button></div>{error&&<p role="alert">{error}</p>}{result&&<div style={{padding:18,borderLeft:'3px solid #9b4940',background:'#f3f1eb',marginTop:12}}><small>{t('Machine translation','Traduction automatique')} · {result.sourceLanguage.toUpperCase()} → {result.targetLanguage.toUpperCase()}</small><p style={{whiteSpace:'pre-wrap'}}>{result.text}</p><button type="button" className="secondary" onClick={speaking?stop:listen}>{speaking?t('Stop audio','Arrêter l’audio'):t('Listen · device voice','Écouter · voix de l’appareil')}</button><p><small>{t('Synthetic reading of the translation, not the speaker’s voice.','Lecture synthétique de la traduction, pas la voix de l’orateur.')}</small></p>{result.warnings?.map(w=><small key={w}>{w}</small>)}</div>}</div>;
}
