import React,{useState} from 'react';
import {pilotApi as api} from '../services/pilotApi.js';
import './profile.css';
import {cantonName} from './cantons.js';
export default function PoliticianProfile({person:p,language,onUpdate}){
 const fr=language==='fr',t=(en,frText)=>fr?frText:en;
 const [tab,setTab]=useState(()=>{try{return new URLSearchParams(location.search).get('tab')==='votes'?'votes':'about';}catch{return 'about';}}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[filter,setFilter]=useState(''),[year,setYear]=useState(''),[page,setPage]=useState(0),[topic,setTopic]=useState(''),[draft,setDraft]=useState(null),[copied,setCopied]=useState(false);
 const date=v=>v?new Date(v).toLocaleDateString(fr?'fr-CH':'en-GB'):'—';
 const votes=p.votes.filter(v=>(!year||v.date?.startsWith(year))&&`${v.title||''} ${v.subject||''} ${v.businessId}`.toLowerCase().includes(filter.toLowerCase()));
 const email=p.contacts?.find(c=>c.kind==='email');
 async function refresh(){setBusy(true);setError('');try{onUpdate(await api.refreshProfile(p.id));}catch{setError(t('The official source could not be refreshed. The previous snapshot remains available.','Impossible d’actualiser la source officielle. Les données précédentes restent disponibles.'));}finally{setBusy(false);}}
 async function generate(e){e.preventDefault();setBusy(true);setError('');setCopied(false);try{setDraft(await api.draftMessage({personId:p.id,topic,language}));}catch{setError(t('The draft model is unavailable. You can still use the verified contact link.','Le modèle est indisponible. Le contact vérifié reste accessible.'));}finally{setBusy(false);}}
 return <div className="politician-profile"><div className="profile-identity">{p.portraitUrl&&<img src={p.portraitUrl} alt={p.name} onError={e=>e.currentTarget.hidden=true}/>}<div><p>{t('Canton','Canton')}: {cantonName(p.canton,language)} · {p.council}</p><strong>{p.party||p.group}</strong>{p.firstJoined&&<p>{t('First entered Parliament','Première entrée au Parlement')} {date(p.firstJoined)}</p>}<p>{t('Current recorded term began','Début du mandat actuel')} {date(p.joined)}</p><p>{t('Parliamentary group','Groupe parlementaire')}: {p.group||'—'}</p>{p.officialUrl&&<a href={p.officialUrl} target="_blank" rel="noreferrer">{t('Official Parliament biography ↗','Biographie officielle ↗')}</a>}{p.left&&<p>{t('Term ended','Fin du mandat')}: {date(p.left)}</p>}{p.portraitUrl&&<small><a href={p.portraitUrl} target="_blank" rel="noreferrer">{t('Portrait: Swiss Parliamentary Services','Portrait : Services du Parlement')} ↗</a></small>}</div></div>
 <div className="profile-tabs" role="group" aria-label={t('Profile sections','Sections du profil')}>{[['about','About','Profil'],['votes','Votes','Votes'],['contact','Write a message','Écrire']].map(([id,en,frText])=><button key={id} aria-pressed={tab===id} onClick={()=>setTab(id)}>{t(en,frText)}{id==='votes'?` · ${p.votes.length.toLocaleString()}`:''}</button>)}</div>
 {tab==='about'&&<><div className="profile-facts">{p.occupations?.map((o,i)=><div key={i}><small>{t('Declared occupation','Profession déclarée')}</small><p>{o.title} · {o.employer}</p><a href={o.sourceUrl} target="_blank" rel="noreferrer">{t('Official record','Donnée officielle')} ↗</a></div>)}{p.elected&&<div><small>{t('Elected','Élection')}</small><p>{date(p.elected)}</p><a href={p.officialUrl||p.sourceUrl} target="_blank" rel="noreferrer">{t('Official membership','Mandat officiel')} ↗</a></div>}</div>
 {!!p.committees?.length&&<details><summary>{t('Committee work','Travail en commission')} · {p.committees.length}</summary>{p.committees.map(c=><p key={c.name}><a href={c.sourceUrl} target="_blank" rel="noreferrer">{c.name}</a><br/><small>{c.role}</small></p>)}</details>}
 {!!p.membershipHistory?.length&&<section className="profile-history"><h3>{t('Parliamentary service','Mandats parlementaires')}</h3>{p.membershipHistory.map(h=><p key={h.id}><strong>{date(h.start)} – {h.end?date(h.end):t('present','aujourd’hui')}</strong><br/>{h.council} · {cantonName(h.canton,language)}</p>)}</section>}
 {p.declaredMandates&&<details open><summary>{t('Declared background','Parcours déclaré')}</summary><p>{p.declaredMandates}</p><small>{t('Original declared wording; dates appear where supplied. These are not necessarily current roles.','Texte original déclaré ; dates lorsqu’elles sont fournies. Ces fonctions ne sont pas nécessairement actuelles.')}</small><p><a href={p.officialUrl||p.sourceUrl} target="_blank" rel="noreferrer">{t('Official record','Donnée officielle')} ↗</a></p></details>}
 {p.partyBackground?<div className="profile-party"><h3>{t('The party’s priorities','Priorités du parti')}</h3><small>{t('Party self-description · reviewed summary, not this person’s individual platform','Présentation du parti · résumé vérifié, distinct des positions individuelles')}</small><div className="profile-topics">{p.partyBackground.topics.map(x=><span key={x.id}>{x.label[fr?'fr':'en']}</span>)}</div><a href={p.partyBackground.sourceUrl} target="_blank" rel="noreferrer">{t('Read the party’s description','Lire la présentation du parti')} ↗</a></div>:<p className="profile-note">{t('Party priorities have not yet been reviewed for this profile.','Les priorités du parti ne sont pas encore vérifiées pour ce profil.')}</p>}
 <p className="profile-note">{p.speeches.length} {t('imported speech passages below. Personal positions stay attached to their dated sources; no inferred political spectrum or stance-change score.','extraits importés ci-dessous. Les positions restent liées aux sources datées ; aucun score de changement de position.')}</p></>}
 {tab==='votes'&&<><p className="profile-note">{p.voteHistory?t('All records returned by the official individual-vote query. This service covers National Council roll calls; it does not establish a complete political career archive.','Tous les résultats de la requête officielle des votes individuels. Ce service couvre les scrutins du Conseil national, pas toutes les décisions d’une carrière.'):t('Only selected roll calls are loaded. Load the official profile to expand this history.','Seuls certains scrutins sont importés. Chargez le profil officiel pour enrichir cet historique.')} {t('Missing records are not abstentions.','Une donnée manquante n’est pas une abstention.')}</p>
 <div className="profile-vote-filters"><input aria-label={t('Search vote titles','Chercher dans les votes')} placeholder={t('Search proposal or subject…','Objet ou sujet…')} value={filter} onChange={e=>{setFilter(e.target.value);setPage(0);}}/><select aria-label={t('Year','Année')} value={year} onChange={e=>{setYear(e.target.value);setPage(0);}}><option value="">{t('All years','Toutes les années')}</option>{[...new Set(p.votes.map(v=>v.date?.slice(0,4)).filter(Boolean))].map(y=><option key={y}>{y}</option>)}</select></div>
 <p><small>{votes.length} {t('matching records','résultats')} · {t('Original official labels','Libellés officiels originaux')}</small></p>{votes.slice(page*20,page*20+20).map(v=><details className="profile-vote" key={v.id}><summary><span><small>{date(v.date)} · {v.businessId}</small>{v.title||v.subject||v.billTitle||v.voteId}</span><strong>{v.decisionText}</strong></summary><p>{v.subject}</p><p>{t('Yes means','Oui signifie')}: {v.meaningYes||'—'}<br/>{t('No means','Non signifie')}: {v.meaningNo||'—'}</p><p>{t('Group at the time','Groupe au moment du vote')}: {v.group}</p><a href={v.sourceUrl} target="_blank" rel="noreferrer">{t('Official vote record','Vote officiel')} ↗</a></details>)}<div className="profile-pages"><button disabled={!page} onClick={()=>setPage(n=>n-1)}>← {t('Previous','Précédent')}</button><span>{page+1} / {Math.max(1,Math.ceil(votes.length/20))}</span><button disabled={(page+1)*20>=votes.length} onClick={()=>setPage(n=>n+1)}>{t('Next','Suivant')} →</button></div></>}
 {tab==='contact'&&<><h3>{t('A question, in your own words.','Une question, avec vos mots.')}</h3><p>{t('Draft a message, review it, then open your email app. Nothing is sent here.','Préparez et relisez votre message, puis ouvrez votre messagerie. Rien n’est envoyé ici.')}</p>{p.contacts?.map(c=><p key={c.href}><a href={c.href} target={c.kind==='website'?'_blank':undefined} rel="noreferrer">{c.value} ↗</a> <a className="profile-contact-source" href={c.sourceUrl} target="_blank" rel="noreferrer">{t('Verified source','Source vérifiée')}</a></p>)}{!p.contacts?.length&&<p>{t('No verified professional contact imported yet.','Aucun contact professionnel vérifié importé.')}</p>}
 <form onSubmit={generate}><label htmlFor="message-topic">{t('What would you like to ask?','Que souhaitez-vous demander ?')}</label><textarea id="message-topic" maxLength={1500} rows={3} value={topic} onChange={e=>setTopic(e.target.value)} required/><button className="primary" disabled={busy||!topic.trim()}>{t('Draft with Cleisthenes','Rédiger avec Cleisthenes')}</button></form>
 {draft&&<div className="profile-draft"><small>{t('AI draft · editable · check before sending','Brouillon IA · modifiable · à vérifier')}</small><label htmlFor="message-subject">{t('Subject','Objet')}</label><input id="message-subject" value={draft.subject} maxLength={200} onChange={e=>setDraft(d=>({...d,subject:e.target.value}))}/><label htmlFor="message-body">{t('Message','Message')}</label><textarea id="message-body" rows={10} value={draft.body} maxLength={6000} onChange={e=>setDraft(d=>({...d,body:e.target.value}))}/><div className="profile-pages"><button onClick={async()=>{try{await navigator.clipboard.writeText(draft.subject+'\n\n'+draft.body);setCopied(true);}catch{setError(t('Select and copy the text manually.','Sélectionnez et copiez le texte manuellement.'));}}}>{copied?t('Copied','Copié'):t('Copy draft','Copier')}</button>{email&&<a href={email.href+'?subject='+encodeURIComponent(draft.subject)+'&body='+encodeURIComponent(draft.body)}>{t('Open email app','Ouvrir la messagerie')} ↗</a>}</div></div>}</>}
 <footer className="profile-refresh"><small>{t('Official snapshot','Données officielles du')} {date(p.voteHistory?.retrievedAt||p.retrievedAt)}</small><button disabled={busy} onClick={refresh}>{busy?t('Working…','Chargement…'):p.voteHistory?t('Refresh official records','Actualiser les données'):t('Load official profile & vote history','Charger le profil et ses votes')}</button></footer>{error&&<p role="alert">{error}</p>}
 </div>;
}
