import React from 'react';
import {languageNames} from './i18n.js';
export function readPreferences(){try{const p=JSON.parse(localStorage.getItem('swiss-reading-preferences')||'{}');return {largeText:p.largeText===true,reduceMotion:p.reduceMotion===true};}catch{return {largeText:false,reduceMotion:false};}}
export default function Settings({language,onLanguage,preferences,onPreferences,user,authAvailable,onAccount,onExplore}){
 const fr=language==='fr',t=(a,b)=>fr?b:a;
 return <section className="settings-page"><p className="eyebrow">{t('Make yourself at home','À votre rythme')}</p><h1>{t('Your reading space.','Votre espace de lecture.')}</h1><p className="page-lead">{t('A few choices for a clearer, calmer experience. Signed-in preferences sync to your account; anonymous preferences stay in this browser.','Les préférences des utilisateurs connectés sont synchronisées avec leur compte. Sans compte, elles restent dans ce navigateur.')}</p>
 <div className="settings-section"><h2>{t('Reading & language','Lecture et langue')}</h2><label className="setting-row"><span><strong>{t('Interface language','Langue de l’interface')}</strong><small>{t('Original sources retain their language. Translation is available beside passages.','Les sources conservent leur langue. Traduisez les extraits sur place.')}</small></span><select aria-label={t('Preferred language','Langue préférée')} value={language} onChange={e=>onLanguage(e.target.value)}>{Object.entries(languageNames).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label>
 <label className="setting-row"><span><strong>{t('Larger reading text','Texte de lecture agrandi')}</strong><small>{t('Give quotations and explanations more room.','Pour lire plus facilement les extraits et explications.')}</small></span><input type="checkbox" checked={preferences.largeText} onChange={e=>onPreferences({...preferences,largeText:e.target.checked})}/></label>
 <label className="setting-row"><span><strong>{t('Reduce motion','Réduire les animations')}</strong><small>{t('Use a still introduction and quieter transitions. Your system preference is also respected.','Une introduction fixe et des transitions discrètes. Le réglage du système est aussi respecté.')}</small></span><input type="checkbox" checked={preferences.reduceMotion} onChange={e=>onPreferences({...preferences,reduceMotion:e.target.checked})}/></label></div>
 <div className="settings-section"><h2>{t('Account & saved sources','Compte et sources enregistrées')}</h2><div className="setting-row"><span><strong>{user?.email||t('Reading without an account','Lecture sans compte')}</strong><small>{user?t('Saved sources are linked to your account.','Les sources enregistrées sont liées à votre compte.'):authAvailable?t('Sign in to save dossier sources. Public reading is always open.','Connectez-vous pour enregistrer des sources. La lecture reste ouverte.'):t('Account saving is not configured in this preview. Reading and local chats are available.','L’enregistrement dans un compte n’est pas configuré. Lecture et conversations locales restent disponibles.')}</small></span><button className="secondary" onClick={onAccount}>{user?t('Manage account','Gérer le compte'):t('Account details','Détails du compte')}</button></div></div>
 <div className="settings-section"><h2>{t('Your conversations','Vos conversations')}</h2><p>{t('New signed-in chats sync to your account. Anonymous chats stay in this browser; import them explicitly from Cleisthenes if you wish. Open Recent chats to revisit or delete a conversation. Questions and their supporting passages are sent to the configured AI service when you ask for an answer.','Les nouvelles conversations connectées sont synchronisées avec votre compte. Sans compte, elles restent dans ce navigateur et peuvent être importées explicitement dans Cleisthenes. Retrouvez ou supprimez une conversation dans les conversations récentes. Vos questions et leurs extraits sont envoyés au service IA configuré pour produire une réponse.')}</p><p>{t('This pilot does not collect identity documents or cast official votes. Private eligibility proofs remain a future concept.','Ce pilote ne recueille pas de pièces d’identité et ne vote pas. Les preuves privées d’éligibilité restent un concept futur.')}</p></div><button className="text-button" onClick={onExplore}>{t('Return to Parliament →','Retour au Parlement →')}</button></section>;
}
