import React,{useState,useEffect,useRef} from 'react';
import {ArrowRight,ArrowLeft,ArrowUpRight,BookOpen,BookmarkSimple,Check,Globe,Hamburger,ShieldCheck,FileText,MagnifyingGlass,Scales,Sparkle,X,Download,UserCircle} from '@phosphor-icons/react';
import {pilotApi as api} from '../services/pilotApi.js';
import {dictionaries,languageNames,categoryNames} from './i18n.js';
import './pilot.css';
import ParliamentExplorer from './ParliamentExplorer.jsx';
import Cleisthenes from './Cleisthenes.jsx';
import {attribution} from './attributions.js';

const initialRoute=()=>{const q=new URLSearchParams(location.search);return {id:q.get('issue'),view:q.get('view')||'explore'};};
export function SwissPilot(){
 const [lang,setLang]=useState(()=>localStorage.getItem('swiss-language')||'en');const t=dictionaries[lang]||dictionaries.en;
 const [chatContext,setChatContext]=useState(null);const [route,setRoute]=useState(initialRoute);const [dossiers,setDossiers]=useState([]);const [dossier,setDossier]=useState(null);const [health,setHealth]=useState(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 const [query,setQuery]=useState('');const [tab,setTab]=useState('overview');const [question,setQuestion]=useState('');const [answer,setAnswer]=useState(null);const [active,setActive]=useState(null);const [selected,setSelected]=useState([]);
 const [user,setUser]=useState(null);const [saved,setSaved]=useState([]);const [modal,setModal]=useState(null);const [authNote,setAuthNote]=useState('');const dialog=useRef(null);const video=useRef(null);const [videoError,setVideoError]=useState(false);const requestId=useRef(0);
 const local=value=>value?.[lang]||value?.en||'';const date=value=>new Intl.DateTimeFormat(lang==='rm'?'de-CH':lang,{day:'numeric',month:'long',year:'numeric'}).format(new Date(value+'T12:00:00'));
 const category=value=>categoryNames[lang]?.[value]||value;
 function navigate(id=null,view='explore'){const url=new URL(location.href);url.search='';if(id)url.searchParams.set('issue',id);if(view!=='explore')url.searchParams.set('view',view);history.pushState({},'',url);setRoute({id,view});setError('');window.scrollTo(0,0);}
 async function boot(){try{const [ds,h]=await Promise.all([api.dossiers(),api.health()]);setDossiers(ds);setHealth(h);}catch{setError(t.error);}}
 useEffect(()=>{boot();api.me().then(setUser).catch(()=>{});const pop=()=>setRoute(initialRoute());addEventListener('popstate',pop);return()=>removeEventListener('popstate',pop);},[]);
 useEffect(()=>{document.documentElement.lang=lang;document.title='Midnight Vote — Swiss Pilot';localStorage.setItem('swiss-language',lang);setAnswer(null);requestId.current++;setBusy(false);},[lang]);
 useEffect(()=>{let ignore=false;setDossier(null);setAnswer(null);setActive(null);setSelected([]);setQuestion('');setTab('overview');requestId.current++;setBusy(false);if(route.id)api.dossier(route.id).then(d=>{if(!ignore)setDossier(d);}).catch(()=>{if(!ignore)setError(t.error);});return()=>{ignore=true;};},[route.id]);
 useEffect(()=>{if(user)api.saved().then(setSaved).catch(()=>{setUser(null);setSaved([]);});else setSaved([]);},[user]);
 useEffect(()=>{if(modal)dialog.current?.showModal();else dialog.current?.close();},[modal]);
 useEffect(()=>{setVideoError(false);if(active?.kind==='video'&&video.current)video.current.currentTime=active.start;},[active]);
 const currentText=e=>e.translations?.[lang]||e.text;
 async function ask(action='explain',q=question){setError('');setBusy(true);const rid=++requestId.current;try{const result=await api.ask({dossierId:dossier.id,action,question:q,language:lang});if(rid===requestId.current)setAnswer(result);}catch{if(rid===requestId.current)setError(t.error);}finally{if(rid===requestId.current)setBusy(false);}}
 async function save(e){if(!user){setAuthNote('');setModal('auth');return;}try{setSaved(await (saved.some(s=>s.id===e.id)?api.remove(e.id):api.save(e.id)));}catch(err){if(err.status===401){setUser(null);setModal('auth');}setError(t.error);}}
 async function exportBrief(){try{const {markdown}=await api.brief({dossierId:dossier.id,evidenceIds:selected,language:lang});const url=URL.createObjectURL(new Blob([markdown],{type:'text/markdown;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`midnight-${dossier.id}-brief.md`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch{setError(t.error);}}
 async function authenticate(event){event.preventDefault();setAuthNote('');setBusy(true);const data=new FormData(event.currentTarget);try{const payload={email:data.get('email'),password:data.get('password')};if(event.nativeEvent.submitter?.value==='signup'){await api.signup(payload);setAuthNote(t.checkEmail);}else{setUser(await api.login(payload));setModal(null);}}catch{setAuthNote(t.accountError);}finally{setBusy(false);}}
 function inspect(e){setActive(e);setTimeout(()=>document.getElementById('evidence-inspector')?.scrollIntoView({behavior:'smooth',block:'nearest'}),30);}
 function EvidenceCard({e,compact=false}){const isSaved=saved.some(s=>s.id===e.id);return <article className={`evidence-card ${compact?'compact':''}`}><div className="evidence-meta"><span>{e.kind==='video'?t.video:t.document}</span><span>{e.language.toUpperCase()}</span></div><h3>{e.sourceKind==='federal-council-explainer'?t.federalExplainer:attribution(e.attribution,lang)}</h3><p>{currentText(e)}</p><div className="card-actions"><button onClick={()=>inspect(e)}><ArrowUpRight/>{t.inspect}</button><button aria-label={isSaved?t.remove:t.save} onClick={()=>save(e)}><BookmarkSimple weight={isSaved?'fill':'regular'}/></button>{route.view==='research'&&<button aria-label={selected.includes(e.id)?t.unselect:t.select} aria-pressed={selected.includes(e.id)} onClick={()=>setSelected(s=>s.includes(e.id)?s.filter(id=>id!==e.id):[...s,e.id])}>{selected.includes(e.id)?<Check/>:<FileText/>}</button>}</div></article>;}
 const visible=dossiers.filter(d=>(local(d.shortTitle)+' '+local(d.summary)).toLowerCase().includes(query.toLowerCase()));
 return <div className="swiss-app"><a className="skip" href="#main">{t.overview}</a><header className="swiss-header"><button className="wordmark" onClick={()=>navigate()}><BookOpen weight="duotone" size={30}/><span>midnight<span className="wordmark-light">.vote</span><small>{t.pilot}</small></span></button><nav aria-label="Main"><button className={route.view==='parliament'?'current':''} onClick={()=>navigate(null,'parliament')}>{lang==='fr'?'Parlement':'Parliament'}</button><button className={route.view==='explore'?'current':''} onClick={()=>navigate(route.id)}>{t.explore}</button><button className={route.view==='research'?'current':''} onClick={()=>navigate(route.id||'eid','research')}>{t.research}</button><button className={route.view==='saved'?'current':''} onClick={()=>navigate(null,'saved')}><BookmarkSimple/>{t.saved}</button></nav><div className="header-tools"><label className="language-select"><Globe/><span className="sr-only">{t.language}</span><select aria-label={t.language} value={lang} onChange={e=>setLang(e.target.value)}>{Object.entries(languageNames).map(([code,name])=><option key={code} value={code}>{name}</option>)}</select></label><button className="account-button" aria-label={user?t.account:t.signin} onClick={()=>{setAuthNote('');setModal('auth');}}><UserCircle/><span>{user?t.account:t.signin}</span></button></div></header>
 {error&&<div role="alert" className="error-banner">{error}<button onClick={()=>{setError('');boot();}}>{t.retry}</button></div>}
 {!['en','fr'].includes(lang)&&<div className="locale-note">{languageNames[lang]} · {lang==='rm'?'Texts uffizials e navigaziun; ulteriurs texts per englais.':'Navigation and dossier summaries translated; detailed research falls back to the available source language.'}</div>}
 <main id="main" className={route.view==='research'?'research-main':''}>
 {!route.id&&!['saved','parliament','chat'].includes(route.view)&&<><section className="intro"><div><p className="eyebrow">{t.eyebrow}</p><h1>{t.headline.split('\n').map((line,i)=><React.Fragment key={line}>{i>0&&<br/>}{line}</React.Fragment>)}</h1><p className="intro-copy">{t.intro}</p><div className="trust-line"><ShieldCheck/>{t.backed}<span>EN / FR / DE / IT / RM</span></div></div><aside className="issue-index"><span className="index-number">01 — 05</span><p>{t.collection}</p><div className="index-rule"/><span>{t.independent}</span></aside></section>
 {dossiers[0]&&<section className="featured-dossier"><div className="feature-content"><p className="eyebrow">{t.featured} <span>01 / {category(dossiers[0].category)}</span></p><h2>{local(dossiers[0].title)}</h2><p>{local(dossiers[0].summary)}</p><button className="primary" onClick={()=>navigate('eid')}>{t.read}<ArrowRight/></button></div><div className="feature-context"><div><span>{t.historical}</span><strong>{date(dossiers[0].date)}</strong></div><div><span>{t.resultLabel}</span><strong><Check size={22}/>{t.accepted}</strong></div><div className="feature-footer"><FileText/><span>{t.editorial}<br/><small>{dossiers[0].readingMinutes} {t.minutes}</small></span></div></div></section>}
 <section className="collection"><div className="section-heading"><div><p className="eyebrow">{t.explore}</p><h2>{t.collection}</h2><p>{t.collectionSub}</p></div><label className="search-field"><MagnifyingGlass/><input aria-label={t.search} placeholder={t.search} value={query} onChange={e=>setQuery(e.target.value)}/></label></div><div className="dossier-grid">{visible.map((d,i)=><button className="dossier-card" key={d.id} onClick={()=>navigate(d.id)}><div className="dossier-card-top"><span>{category(d.category)}</span><span>{String(i+1).padStart(2,'0')}</span></div><h3>{local(d.shortTitle)}</h3><p>{local(d.summary)}</p><div className="dossier-card-bottom"><span>{date(d.date)}<small>{t[d.result]} · {t.historical}</small></span><ArrowUpRight size={24}/></div></button>)}</div>{!visible.length&&<p>{t.insufficient}</p>}</section><section className="identity-banner"><ShieldCheck size={32}/><div><span className="eyebrow">{t.concept}</span><h2>{t.privacy}</h2><p>{t.privacyIntro}</p></div><button className="text-button" onClick={()=>setModal('identity')}>{t.consent}<ArrowRight/></button></section></>}
 {route.id&&!dossier&&!error&&<p role="status">{t.working}</p>}
 {dossier&&<><button className="back-button" onClick={()=>navigate()}><ArrowLeft/>{t.back}</button><section className="dossier-heading"><p className="eyebrow">{category(dossier.category)} <span> / {t.historical}</span></p><h1>{local(dossier.shortTitle)}</h1><p>{local(dossier.summary)}</p><div className="dossier-facts"><span>{date(dossier.date)}</span><span className={`outcome ${dossier.result}`}>{t[dossier.result]}</span><span>{dossier.readingMinutes} {t.minutes}</span></div></section>
 <div className="workbench"><div className="reading-pane"><div className="tabs" role="tablist">{['overview','compare','evidence'].map(key=><button key={key} role="tab" aria-selected={tab===key} onClick={()=>setTab(key)}>{t[key]}</button>)}</div>
 {tab==='overview'&&dossier.evidence.some(e=>e.kind==='video')&&<section className="official-videos"><p className="eyebrow">{t.watchOfficial}</p><p className="muted">{t.videoCoverage}</p><div className="skill-actions">{dossier.evidence.filter(e=>e.kind==='video').map(e=><button key={e.id} onClick={()=>inspect(e)}>{languageNames[e.language]} ↗</button>)}</div></section>}
 {tab==='overview'&&<section className="overview-panel"><p className="eyebrow">{t.voteContext}</p><h2>{local(dossier.question)}</h2><p className="muted">{t.archiveNote}</p><EvidenceCard e={dossier.evidence[0]}/><div className="argument-preview">{dossier.evidence.filter(e=>['support','opposition'].includes(e.stance)).map(e=><div key={e.id}><span className="argument-label">{e.stance==='support'?t.support:t.opposition}</span><p>{currentText(e)}</p><button className="text-button" onClick={()=>inspect(e)}>{t.source}<ArrowUpRight/></button></div>)}</div></section>}
 {tab==='compare'&&<section className="comparison-grid">{['support','opposition'].map(stance=><div key={stance}><h2><Scales/>{t[stance]}</h2>{dossier.evidence.filter(e=>e.stance===stance).map(e=><EvidenceCard key={e.id} e={e}/>)}</div>)}</section>}
 {tab==='evidence'&&<section className="evidence-list"><p className="muted">{dossier.evidence.some(e=>e.kind==='video')?t.review:t.coverage}</p>{dossier.evidence.map(e=><EvidenceCard e={e} key={e.id}/>)}</section>}
 <section className="ask-box"><div className="ask-title"><Sparkle/><h2>{t.ask}</h2></div><div className="skill-actions">{['explain','compare','translate','brief'].map(action=><button disabled={busy} key={action} onClick={()=>ask(action,'')}>{t[action]}</button>)}</div><form onSubmit={e=>{e.preventDefault();ask();}}><label className="sr-only" htmlFor="question">{t.ask}</label><input id="question" placeholder={t.askPlaceholder} value={question} onChange={e=>setQuestion(e.target.value)} maxLength={1000}/><button className="primary" disabled={busy||!question.trim()}>{busy?t.working:t.send}<ArrowRight/></button></form><small>{health?.ai==='recorded-replay'?t.replay:health?.ai==='configured-not-verified'?t.live:t.extracts}</small>
 {answer&&<div className="answer" aria-live="polite"><span className="eyebrow">{answer.mode==='recorded-replay'?t.replay:answer.mode==='live-inference'?t.live:t.extracts}</span>{answer.status!=='ok'?<p>{answer.status==='translation-unavailable'?t.translationUnavailable:t.insufficient}</p>:answer.claims.map((claim,i)=><p key={i}>{claim.text} <button className="citation" aria-label={`${t.inspect} ${i+1}`} onClick={()=>inspect(dossier.evidence.find(e=>e.id===claim.evidenceId))}>[{i+1}]</button></p>)}</div>}</section>
 </div><aside className="source-pane" id="evidence-inspector" aria-label={t.evidence}>{active?<><div className="inspector-heading"><span className="eyebrow">{active.kind==='video'?t.video:t.document} / {active.language.toUpperCase()}</span><button aria-label={t.close} onClick={()=>setActive(null)}><X/></button></div><h2>{active.sourceKind==='federal-council-explainer'?t.federalExplainer:attribution(active.attribution,lang)}</h2>{active.kind==='video'&&<><video ref={video} controls preload="metadata" key={active.id} src={active.mediaUrl} onLoadedMetadata={()=>{video.current.currentTime=active.start;}} onError={()=>setVideoError(true)}/><button className="secondary" onClick={()=>{video.current.currentTime=active.start;video.current.play().catch(()=>setVideoError(true));}}>{t.play}</button>{videoError&&<p role="alert">{t.videoError}</p>}</>}<p className="eyebrow">{active.reviewState==='official-publisher-captions'?t.publisherCaption:t.editorial}</p><blockquote>{active.text}</blockquote>{active.translations?.[lang]&&active.translations[lang]!==active.text&&<><span className="eyebrow">{t.translation}</span><p>{active.translations[lang]}</p></>}<a className="source-link" href={active.source.url} target="_blank" rel="noreferrer">{active.source.title}<ArrowUpRight/></a><small>{active.id} · r{active.revision}<br/>{active.reviewState==='official-publisher-captions'?t.publisherCaption:t.review}</small><button className="secondary" onClick={()=>save(active)}><BookmarkSimple/>{saved.some(s=>s.id===active.id)?t.remove:t.save}</button></>:<><FileText size={32}/><h2>{t.readSource}</h2><p>{dossier.evidence.some(e=>e.kind==='video')?t.videoCoverage:t.coverage}</p><div className="source-directory">{dossier.sources.map(s=><a key={s.id} href={s.url} target="_blank" rel="noreferrer">{s.title}<ArrowUpRight/></a>)}</div></>}
 {route.view==='research'&&<section className="brief-builder"><h3>{t.selected} <span>{selected.length}</span></h3>{selected.length?<><ul>{selected.map(id=><li key={id}>{dossier.evidence.find(e=>e.id===id)?.attribution}<button aria-label={t.remove} onClick={()=>setSelected(s=>s.filter(x=>x!==id))}><X/></button></li>)}</ul><button className="primary" onClick={exportBrief}><Download/>{t.export}</button></>:<p>{t.emptySelection}</p>}</section>}
 </aside></div>{dossier.id==='eid'&&<section className="romansh-passage"><span className="eyebrow">{t.rm}</span><p lang="rm">{dossier.evidence.find(e=>e.id==='rm-civic-passage')?.text}</p><small>{t.rmNote}</small><a href="https://www.bk.admin.ch/rm" target="_blank" rel="noreferrer">Chanzlia federala <ArrowUpRight/></a></section>}</>}
 {route.view==='parliament'&&<ParliamentExplorer language={lang} onContext={setChatContext}/>}
 {route.view==='saved'&&<section className="saved-page"><p className="eyebrow">{t.saved}</p><h1>{t.savedTitle}</h1><p>{user?t.savedIntro:t.loginNeeded}</p>{!user?<button className="primary" onClick={()=>setModal('auth')}>{t.signin}<ArrowRight/></button>:saved.length?<div className="dossier-grid">{saved.map(e=><article className="evidence-card" key={e.id}><h3>{e.sourceKind==='federal-council-explainer'?t.federalExplainer:attribution(e.attribution,lang)}</h3><p>{currentText(e)}</p><button onClick={()=>navigate(e.dossierId,'research')}>{t.read}<ArrowRight/></button><button onClick={()=>save(e)}>{t.remove}</button></article>)}</div>:<p>{t.emptySaved}</p>}</section>}
 </main>{route.view==='chat'?null:<footer className="swiss-footer"><span>midnight.vote <small>{t.pilot}</small></span><p>{t.independent}<br/>{t.noVote}</p><button onClick={()=>setModal('identity')}><ShieldCheck/>{t.privacy}</button></footer>}
 <Cleisthenes language={lang} expanded={route.view==='chat'} onExpand={()=>navigate(null,'chat')} onCollapse={()=>navigate(null,'parliament')} context={route.id?{kind:'dossier',id:route.id,title:dossier?.shortTitle?.[lang]||dossier?.shortTitle?.en}:chatContext}/>
 <dialog ref={dialog} onCancel={()=>setModal(null)} onClose={()=>setModal(null)}><button className="dialog-close" aria-label={t.close} onClick={()=>setModal(null)}><X/></button>{modal==='auth'?<><UserCircle size={32}/><h2>{user?t.account:t.signin}</h2>{user?<><p>{user.email}</p><button className="primary" onClick={async()=>{try{await api.logout();setUser(null);setModal(null);}catch{setAuthNote(t.error);}}}>{t.signout}</button></>:<><p>{t.loginNeeded}</p>{!health?.auth?<p className="notice">{t.authUnavailable}</p>:<form onSubmit={authenticate}><label>{t.email}<input name="email" type="email" required autoComplete="email"/></label><label>{t.password}<input name="password" type="password" required minLength={8} autoComplete="current-password"/></label><button className="primary" disabled={busy} value="login">{t.signin}</button><button className="secondary" disabled={busy} value="signup">{t.create}</button></form>}</>}{authNote&&<p role="status">{authNote}</p>}</>:<><ShieldCheck size={36}/><p className="eyebrow">{t.concept}</p><h2>{modal==='consent'?t.consentTitle:t.privacy}</h2><p>{modal==='consent'?t.consentText:t.privacyText}</p><button className="primary" onClick={()=>modal==='consent'?setModal(null):setModal('consent')}>{modal==='consent'?t.done:t.consent}<ArrowRight/></button></>}</dialog>
 </div>;
}
