import React,{useEffect,useState} from 'react';
import {pilotApi as api} from '../services/pilotApi.js';
import {categoryNames} from './i18n.js';
const savedFilters=()=>{try{return JSON.parse(sessionStorage.getItem('civic-discovery-filters')||'{}');}catch{return {};}};
export default function Topics({dossiers,language,onNavigate,onAsk}){
 const [q,setQ]=useState(()=>savedFilters().q||''),[category,setCategory]=useState(()=>savedFilters().category||''),[type,setType]=useState(()=>savedFilters().type||'all'),[stage,setStage]=useState(()=>savedFilters().stage||''),[from,setFrom]=useState(()=>savedFilters().from||''),[to,setTo]=useState(()=>savedFilters().to||''),[sourceLanguage,setSourceLanguage]=useState(()=>savedFilters().language||''),[parliament,setParliament]=useState(null),[chosen,setChosen]=useState(null),[detail,setDetail]=useState(null);
 useEffect(()=>{let live=true;api.parliament().then(p=>live&&setParliament(p)).catch(()=>{});return()=>{live=false;};},[]);
 useEffect(()=>{let live=true;setDetail(null);if(chosen)api.parliamentBusiness(chosen.id).then(d=>live&&setDetail(d)).catch(()=>{});return()=>{live=false;};},[chosen?.id]);
 const local=o=>o?.[language]||o?.en||'',normalize=s=>s.normalize('NFD').replace(/\p{M}/gu,'').toLowerCase();
 const rows=[...dossiers.map(d=>({id:d.id,title:local(d.shortTitle),summary:local(d.summary),category:d.category,type:'popular-vote',stage:'completed',date:d.date,language,languages:d.sourceLanguages||[language],original:d})),...(parliament?.businesses||[]).map(b=>({id:b.id,title:b.title,summary:b.status,category:'parliament',type:'proposal',stage:b.statusGroup,date:(b.submitted||b.modified||'').slice(0,10),language:'fr',original:b}))].filter(r=>(type==='all'||r.type===type)&&(!category||r.category===category)&&(!stage||r.stage===stage)&&(!from||r.date>=from)&&(!to||r.date<=to)&&(!sourceLanguage||(r.languages||[r.language]).includes(sourceLanguage))&&normalize(r.title+' '+r.summary).includes(normalize(q)));
 const filters={q,category,type,stage,from,to,language:sourceLanguage};
 useEffect(()=>{try{sessionStorage.setItem('civic-discovery-filters',JSON.stringify(filters));}catch{}},[q,category,type,stage,from,to,sourceLanguage]);
 return <section className="topics-workspace"><p className="eyebrow">Explore the public record</p><h1>Topics & votes</h1><p className="page-lead">Find a proposal, understand the debate, or revisit a popular vote.</p><div className="discovery-search"><label><span className="sr-only">Search topics and proposals</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search a subject, proposal or question…"/></label><button className="primary" onClick={()=>onAsk({kind:'search',id:'topics',title:'Topics · filtered search',filters},{prompt:q||'Help me explore proposals in this selection.'})}>Search with Cleisthenes ↗</button></div><div className="discovery-filters"><label>Topic<select value={category} onChange={e=>setCategory(e.target.value)}><option value="">All topics</option>{[...new Set(dossiers.map(d=>d.category))].map(c=><option key={c} value={c}>{categoryNames[language]?.[c]||c}</option>)}<option value="parliament">Parliamentary proposals</option></select></label><label>Record type<select value={type} onChange={e=>setType(e.target.value)}><option value="all">All records</option><option value="proposal">Parliamentary proposal</option><option value="popular-vote">Popular vote</option></select></label><label>Stage<select value={stage} onChange={e=>setStage(e.target.value)}><option value="">All stages</option><option value="proceedings">In proceedings</option><option value="concluded">Concluded proposal</option><option value="completed">Completed popular vote</option></select></label><label>From<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>To<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><label>Source language<select value={sourceLanguage} onChange={e=>setSourceLanguage(e.target.value)}><option value="">All available</option>{['en','fr','de','it','rm'].map(l=><option key={l} value={l}>{l.toUpperCase()}</option>)}</select></label></div><small>Proposal records are imported in French; dossier summaries use your interface language. Original debate languages are available in Parliament.</small>
 {!q&&!category&&!from&&!to&&!stage&&type==='all'&&<section className="example-dossier"><span className="example-mark">EXAMPLE</span><div><h2>Example dossier: e-ID Act</h2><p>Inspect the proposal, compare the arguments and check the official outcome.</p><small>28 September 2025 · Historical popular vote · Accepted</small></div><button className="secondary" onClick={()=>onNavigate('eid')}>Inspect the dossier →</button></section>}
 <div className="workspace-heading"><h2>{rows.length} records</h2><button className="text-button" onClick={()=>{setQ('');setCategory('');setType('all');setStage('');setFrom('');setTo('');setSourceLanguage('');}}>Reset filters</button></div><div className="discovery-results">{rows.slice(0,60).map(r=><button className="discovery-row" key={r.type+r.id} onClick={()=>r.type==='popular-vote'?onNavigate(r.id):setChosen(r)}><span className="record-type">{r.type==='popular-vote'?'Popular vote':'Proposal'}<small>{r.date}</small></span><span><strong>{r.title}</strong><small>{r.summary}</small></span><span>↗</span></button>)}</div>{rows.length>60&&<p>Showing the first 60. Refine your search to narrow the results.</p>}{!rows.length&&<p>No imported records match these filters. Try a broader selection.</p>}
 {chosen&&<section className="workspace-card proposal-preview"><button className="text-button" onClick={()=>setChosen(null)}>Close selection ×</button><p className="eyebrow">{chosen.original.number} · Parliamentary proposal</p><h2>{chosen.title}</h2><p>{chosen.summary}</p><div className="member-actions"><a href={chosen.original.officialUrl} target="_blank" rel="noreferrer">Official proposal ↗</a><button className="primary" onClick={()=>onAsk({kind:'business',id:chosen.id,title:chosen.title},{prompt:'Explain this proposal and its available debate.'})}>Ask about this proposal</button></div>{detail&&<><h3>Timeline</h3><ol>{detail.timeline.map(e=><li key={e.id}>{e.date?.slice(0,10)} · {e.label}</li>)}</ol><p>{detail.speeches.length} imported passages · {detail.votes.length} recorded proposal votes</p></>}</section>}
 </section>;
}
