import React,{useState} from 'react';
import {pilotApi} from '../services/pilotApi.js';
import {PassageContext} from './DebateReader.jsx';
import PassageTranslation from './PassageTranslation.jsx';
const clock=s=>`${Math.floor(s/60)}:${String(Math.floor(s%60)).padStart(2,'0')}`;
function Highlight({text,ranges=[]}){let end=0;const parts=[];for(const [a,b] of ranges){parts.push(text.slice(end,a),<mark key={a}>{text.slice(a,b)}</mark>);end=b;}parts.push(text.slice(end));return <>{parts}</>;}
export default function VideoSearch({language,onAsk}){
 const fr=language==='fr',t=(a,b)=>fr?b:a;
 const [query,setQuery]=useState(''),[mode,setMode]=useState('spoken'),[result,setResult]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function search(e){e.preventDefault();setBusy(true);setError('');setResult(null);try{setResult(await pilotApi.videoSearch({query,mode}));}catch{setError(mode==='visual'?t('The experimental video service is unavailable. Switch back to debate text to keep reading.','Le service vidéo expérimental est indisponible. Revenez au texte des débats pour poursuivre.'):t('Search could not be completed. Please try again.','La recherche a échoué. Veuillez réessayer.'));}finally{setBusy(false);}}
 function changeMode(value){setMode(value);setResult(null);setError('');}
 return <details className="parliament-coverage-details"><summary>{t('Read the debate','Lire les débats')}</summary>
 <form onSubmit={search} style={{display:'grid',gap:12,margin:'20px 0'}}>
 <p>{t('Find what was said, who said it and the original source. Recordings appear alongside the text when a timed extract is available.','Retrouvez les propos, leur auteur et la source originale. Les extraits vidéo disponibles accompagnent le texte.')}</p>
 <details><summary>{t('Advanced video tools','Outils vidéo avancés')}</summary><div className="video-search-modes" role="group" aria-label={t('Search by','Rechercher par')}>{[['spoken',t('Debate text','Texte des débats')],['visual',t('Video imagery · experimental','Images vidéo · expérimental')]].map(([value,label])=><button type="button" key={value} disabled={busy} aria-pressed={mode===value} onClick={()=>changeMode(value)}>{label}</button>)}</div></details>
 {mode==='visual'?<p>{t('Experimental image similarity across processed recordings. Use an English scene description. Results do not establish what was said or whether the described event occurred.','Similarité visuelle expérimentale sur les enregistrements traités. Décrivez une scène en anglais. Les résultats ne prouvent ni les propos ni la présence de l’événement décrit.')}</p>:<small>{t('Search the original wording in French, German or Italian. For a question in another language, ask Cleisthenes.','Recherchez les termes originaux en français, allemand ou italien. Pour une question dans une autre langue, interrogez Cleisthenes.')}</small>}
 <input placeholder={mode==='spoken'?t('A topic or phrase, e.g. protection des données…','Un thème ou une expression : protection des données…'):'A speaker at a microphone…'} aria-label={t('Search debates','Rechercher dans les débats')} value={query} maxLength={500} disabled={busy} onChange={e=>setQuery(e.target.value)} required/>
 <button disabled={busy||!query.trim()}>{busy?t('Searching…','Recherche…'):t('Search','Rechercher')}</button></form>
 {error&&<p role="alert">{error}</p>}
 {result&&<div aria-live="polite"><small>{result.mode==='visual'?t('Experimental visual matches','Résultats visuels expérimentaux'):t('Original parliamentary text','Texte parlementaire original')} · {result.matches.length} {t('results','résultats')}</small>
 {!result.matches.length&&<p>{t('No matches in the available collection. Try another phrase or ask Cleisthenes a question.','Aucun résultat dans la collection disponible. Essayez une autre expression ou posez une question à Cleisthenes.')}</p>}
 {result.matches.map(m=><article key={m.id} style={{padding:'20px 0',maxWidth:680,borderBottom:'1px solid #e7e1d8'}}><h3>{m.speaker||t('Parliamentary record','Compte rendu parlementaire')}</h3><small>{m.language?.toUpperCase()} · {m.date?.slice(0,10)}</small>{m.text&&<blockquote><Highlight text={m.text} ranges={m.highlights}/></blockquote>}
 {m.corrections?.length>0&&<small>{t('Spelling match','Correspondance approchée')} : {m.corrections.map(c=>`${c.query} → ${c.matched}`).join(', ')}</small>}
 {m.text&&<><PassageTranslation passage={m} language={language}/><button type="button" className="secondary" onClick={()=>onAsk?.({kind:m.personId?'person':'business',id:m.personId||m.businessId,title:m.speaker,passageId:m.id},{prompt:t(`Explain this passage in relation to “${result.query}”.`,`Explique cet extrait en lien avec « ${result.query} ».`).slice(0,500)})}>{t('Ask Cleisthenes about this passage','Interroger Cleisthenes sur cet extrait')}</button></>}
 {m.mediaUrl?<details onToggle={e=>{if(!e.currentTarget.open)e.currentTarget.querySelector('video')?.pause();}}><summary>{result.mode==='visual'?t('Preview images · speech not verified','Aperçu visuel · propos non vérifiés'):t('Watch aligned passage','Voir le passage aligné')} · {clock(m.start)}–{clock(m.end)}</summary><p><small>{result.mode==='visual'?t('Image similarity only. This interval does not establish a spoken match for your query.','Similarité visuelle uniquement. Cet intervalle ne prouve pas une correspondance avec les propos recherchés.'):t('Machine-aligned paragraph · human review pending. The highlighted words are within this passage; word-level timing is not verified.','Paragraphe aligné automatiquement · à vérifier. Le minutage de chaque mot surligné n’est pas vérifié.')}</small></p><video style={{width:'100%',borderRadius:12,marginTop:12}} controls preload="metadata" src={m.mediaUrl+'#t='+m.start+','+m.end} onLoadedMetadata={e=>{e.currentTarget.currentTime=m.start;}} onPlay={e=>{if(e.currentTarget.currentTime>=m.end||e.currentTarget.currentTime<m.start)e.currentTarget.currentTime=m.start;}} onTimeUpdate={e=>{if(e.currentTarget.currentTime>=m.end)e.currentTarget.pause();}}/></details>:<p><small>{t('Read the full intervention at the official source. A timed video extract is not available here yet.','Consultez l’intervention complète dans la source officielle. Aucun extrait vidéo minuté n’est encore disponible ici.')}</small></p>}
 {result.mode!=='visual'&&<PassageContext id={m.id} language={language}/>}<a href={m.sourceUrl} target="_blank" rel="noreferrer">{t('Read the official record ↗','Lire le compte rendu officiel ↗')}</a></article>)}</div>}</details>;
}
