import {mkdirSync,readFileSync,writeFileSync,existsSync,renameSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {openParliament,plainText,officialDate,statusGroup} from '../server/parliament.mjs';
const sessionId=process.argv.find(x=>x.startsWith('--session='))?.split('=')[1]||'5214';if(!/^\d{4}$/.test(sessionId))throw Error('Invalid session');
const dir=`data/parliament/session-${sessionId}`;mkdirSync(dir+'/responses',{recursive:true});
const hash=s=>createHash('sha256').update(s).digest('hex');
const progress={sessionId,status:'running',started:new Date().toISOString(),stage:'discovery',queries:0,cacheHits:0,errors:[]};
function save(){const text=JSON.stringify(progress,null,2);writeFileSync(dir+'/progress.tmp',text);try{renameSync(dir+'/progress.tmp',dir+'/progress.json');}catch(e){if(!['EPERM','EBUSY','EACCES'].includes(e.code))throw e;writeFileSync(dir+'/progress.json',text);}}
async function query(table,filter){const rows=[];for(let skip=0;skip<30000;skip+=200){const u=new URL(table,'https://ws.parlament.ch/odata.svc/');for(const[k,v]of Object.entries({'$format':'json','$filter':filter,'$orderby':table==='SubjectBusiness'?'BusinessNumber asc':'ID asc','$top':'200','$skip':String(skip)}))u.searchParams.set(k,v);const file=dir+'/responses/'+hash(u.href)+'.json';let entry;if(existsSync(file)){entry=JSON.parse(readFileSync(file));if(hash(entry.raw)!==entry.sha256)throw Error('Snapshot checksum mismatch');progress.cacheHits++;}else{const r=await fetch(u,{signal:AbortSignal.timeout(60000)});if(!r.ok)throw Error(`${table}: ${r.status}`);const raw=await r.text();entry={url:u.href,retrievedAt:new Date().toISOString(),raw,sha256:hash(raw)};writeFileSync(file,JSON.stringify(entry));}progress.queries++;const j=JSON.parse(entry.raw),page=Array.isArray(j.d)?j.d:j.d?.results;if(!Array.isArray(page))throw Error('Invalid OData page');rows.push(...page);save();if(page.length<200)return rows;}throw Error('Pagination limit reached');}
const db=openParliament();
function put(kind,row,payload){const text=JSON.stringify(payload),sha=hash(text),url=row.__metadata?.uri;if(!url?.startsWith('https://ws.parlament.ch/'))throw Error('Missing source');db.db.prepare('INSERT OR IGNORE INTO revisions VALUES(?,?,?,?,?)').run(kind,String(payload.id),sha,text,progress.started);db.db.prepare('INSERT OR REPLACE INTO records VALUES(?,?,?,?,?,?)').run(kind,String(payload.id),text,url,progress.started,sha);}
try{
 const session=(await query('Session',`ID eq ${sessionId} and Language eq 'FR'`))[0];if(!session)throw Error('Session not found');
 const meetings=await query('Meeting',`IdSession eq ${sessionId} and Language eq 'FR'`);
 const transcripts=await query('Transcript',`IdSession eq '${sessionId}' and Language eq 'FR'`);
 if(new Set(transcripts.map(t=>t.ID)).size!==transcripts.length)throw Error('Duplicate transcript pagination');
 progress.transcripts=transcripts.length;progress.meetings=meetings.length;progress.stage='subject-links';save();console.log(`Discovered ${meetings.length} meetings and ${transcripts.length} transcript records`);
 const subjects=[...new Set(transcripts.map(t=>String(t.IdSubject)))],links=new Map();
 // Bounded concurrency; each successful source response is a resumable checkpoint.
 for(let i=0;i<subjects.length;i+=4){await Promise.all(subjects.slice(i,i+4).map(async id=>links.set(id,await query('SubjectBusiness',`IdSubject eq ${id}L and Language eq 'FR'`))));progress.subjectsLinked=Math.min(i+4,subjects.length);save();if(i%40===0)console.log(`Subject links ${progress.subjectsLinked}/${subjects.length}`);}
 const businessIds=[...new Set([...links.values()].flat().map(x=>String(x.BusinessNumber)))];progress.stage='business-metadata';save();
 for(let i=0;i<businessIds.length;i+=4){const groups=await Promise.all(businessIds.slice(i,i+4).map(id=>query('Business',`ID eq ${id} and Language eq 'FR'`)));for(const r of groups.flat())put('business',r,{id:String(r.ID),number:r.BusinessShortNumber,title:plainText(r.Title),type:r.BusinessTypeName,status:r.BusinessStatusText,statusGroup:statusGroup(r.BusinessStatusText),statusDate:officialDate(r.BusinessStatusDate),modified:officialDate(r.Modified),submitted:officialDate(r.SubmissionDate),officialUrl:`https://www.parlament.ch/fr/ratsbetrieb/suche-curia-vista/geschaeft?AffairId=${r.ID}`});}
 progress.stage='indexing';save();let paragraphs=0;const mediaJobs=[];const speakers=new Set(),languages={};
 db.db.exec('BEGIN');try{for(const r of transcripts){if(r.DisplaySpeaker!==true||!r.LanguageOfText||!plainText(r.Text))continue;const business=links.get(String(r.IdSubject))?.map(x=>String(x.BusinessNumber))||[];
 const lang=r.LanguageOfText.toLowerCase();languages[lang]=(languages[lang]||0)+1;if(r.PersonNumber)speakers.add(r.PersonNumber);
 const officialUrl=`https://www.parlament.ch/fr/ratsbetrieb/amtliches-bulletin/amtliches-bulletin-die-verhandlungen?SubjectId=${r.IdSubject}&TranscriptId=${r.ID}`;
 for(const [i,text]of String(r.Text).split(/<\/p>/i).map(plainText).filter(Boolean).entries()){
  const id=`${r.ID}-${i}`,p={id,transcriptId:String(r.ID),sessionId,subjectId:String(r.IdSubject),businessId:business[0]||null,businessIds:business,personId:r.PersonNumber?String(r.PersonNumber):null,speaker:r.SpeakerFullName||[r.SpeakerFirstName,r.SpeakerLastName].join(' '),speakerFunction:r.SpeakerFunction,roleReview:'unreviewed',language:lang,date:officialDate(r.StartTimeWithTimezone||r.Start),text,council:r.CouncilName,group:r.ParlGroupAbbreviation,officialUrl,videoStatus:'pending-verification',reviewState:'official-bulletin-import'};
  put('speech',r,p);db.db.prepare('DELETE FROM speech_search WHERE id=?').run(id);db.db.prepare('INSERT INTO speech_search(id,person_id,business_id,text) VALUES(?,?,?,?)').run(id,p.personId,p.businessId,text);paragraphs++;
 }
 mediaJobs.push({id:String(r.ID),sessionId,subjectId:String(r.IdSubject),personId:r.PersonNumber,language:lang,officialPage:officialUrl,stage:'source-verification-pending',asr:'pending',alignment:'pending',vss:'pending',durationHintSeconds:(Date.parse(officialDate(r.End))-Date.parse(officialDate(r.Start)))/1000});
 }
 const payload={id:sessionId,title:session.SessionName,start:officialDate(session.StartDate),end:officialDate(session.EndDate),businessIds,coverage:'All Transcript records returned by the official session query. Speech paragraphs exclude procedural/non-displayed text. Media processing and individual roll-call ingestion are separate stages.',ingestion:{status:'text-indexed',meetings:meetings.length,transcripts:transcripts.length,speeches:mediaJobs.length,paragraphs,speakers:speakers.size,languages,videoAligned:0,vssAnalyzed:0}};put('session',session,payload);db.db.exec('COMMIT');}catch(e){db.db.exec('ROLLBACK');throw e;}
 const queueFile=dir+'/media-jobs.json';const existing=existsSync(queueFile)?JSON.parse(readFileSync(queueFile)):[];writeFileSync(queueFile,JSON.stringify(mediaJobs.map(j=>existing.find(old=>old.id===j.id)||j),null,2));
 progress.status='text-complete';progress.stage='media-pending';progress.paragraphs=paragraphs;progress.speakers=speakers.size;progress.languages=languages;progress.mediaJobs=mediaJobs.length;progress.finished=new Date().toISOString();save();console.log(JSON.stringify(progress,null,2));
}catch(e){progress.status='failed';progress.errors.push(e.message);save();console.error(e.message);process.exitCode=1;}finally{db.close();}
